### ISSUE TITLE
java.time.Instant rather than java.util.Date in the Java target format?

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/concerto#101]
Is it recommended best practice to use Java.time rather than the older (and considered poorly designed) Java.util.date, as currently used by the `concerto-tools` Java target.

## Context

This isn't a bug, but a suggestion for improvement.

## Expected Behavior

CTO concepts making use of the `DateTime` atomic types should generate Java classes with fields using `java.time.Instant`.

## Actual Behavior

CTO concepts making use of the `DateTime` atomic types generate Java classes with fields using `java.util.Date`.

## Possible Fix

Maybe, just this line to change:https://github.com/accordproject/concerto/blob/58a322bf0541c2b5ccd68b60da674efe9f6a9a36/packages/concerto-tools/lib/codegen/fromcto/java/javavisitor.js#L364

**Comment by kishiiv** [comment]
I can do it for you

**Comment by jeromesimeon** [comment]
Sorry I missed this @kishiiv That should be great if you are still up for it!

I would love to get feedback from @dselman or @mttrbrts on this.

In the meantime I'm assigning it to you.

**Comment by jeromesimeon** [comment]
Technical note on this: We probably want to make sure that whatever type we pick plays well with Jackson https://github.com/FasterXML/jackson

We want to make sure that concerto object in JSON format containing DateTime will be loaded as proper JSON objects of class `java.time.Instant` if we make the switch. This should be tested somehow.

**Comment by fluctix** [comment]
i want to work on this

**Comment by Aniruddha-Shriwant** [comment]
May I work on this?

**Comment by subhajit20** [comment]
hey @jeromesimeon  @mttrbrts  can you review my pr once?
