### ISSUE TITLE
Typo in DEVELOPERS.md

### ISSUE THREAD

**Issue by shahsank3t** [accordproject/concerto#115]
**Describe the bug**

1. In DEVELOPERS.md ([here](https://github.com/accordproject/concerto/blob/master/DEVELOPERS.md)), need to replace `Cicero` with `Concerto`.

2. In section building concerto ([here](https://github.com/accordproject/concerto/blob/master/DEVELOPERS.md#building-concerto)), URL of the main repository to be added as upstream has a typo in it. `acccordproject` should be `accordproject` 

**To Reproduce**
1. Go to [DEVELOPERS.md](https://github.com/accordproject/concerto/blob/master/DEVELOPERS.md#building-concerto)
2. Check 'Add the main repository as an upstream remote to your repository'
3. Notice the typo in URL

**Expected behavior**
Instead of `acccordproject`, it should be `accordproject`, and `Cicero` should be replaced with `Concerto`

**Comment by shahsank3t** [comment]
@dselman -  can you please add some labels to this and assign it to me so I could quickly open a PR for this?

**Comment by andrearizzello** [comment]
I can do that :) 👍

**Comment by shahsank3t** [comment]
@andrearizzello  - I've already started on it :)

**Comment by andrearizzello** [comment]
Oh, ok well in that case nevermind :)

**Comment by shahsank3t** [comment]
@andrearizzello - since you already opened a PR, make sure you sign it as well in following way:
` git commit -s -m <you-message>` like DCO check will fail.
In your case right now, you can try the following command:
<img width="808" alt="Screenshot 2019-10-10 at 3 12 05 AM" src="https://user-images.githubusercontent.com/6761317/66522663-96e0e700-eb0b-11e9-98ac-8f38aa2d0199.png">

**Comment by andrearizzello** [comment]
@shahsank3t i added the SignOff to my commit but i still see the error on the PR

**Comment by jeromesimeon** [comment]
Fixed in #117
