### ISSUE TITLE
Link broken in Contributing.md 

### ISSUE THREAD

**Issue by Shivansh2407** [accordproject/concerto#120]
There is a link to Code of Conduct link in contributing.md file that need to be fixed . It is a issue to be solved as soon as possible so that people are aware about accord code of conduct.

**Comment by parammittal16** [comment]
Can I work on it?

**Comment by jeromesimeon** [comment]
sure @parammittal16 !

**Comment by parammittal16** [comment]
@Shivansh2407 can u tell me the link which is to be replaced?
