### ISSUE TITLE
Concerto Model Web Editor

### ISSUE THREAD

**Issue by ankingcodes** [accordproject/concerto#168]
This has been listed as a project idea for Google Summer of Code 2020, mentored by @DianaLease and @irmerk. I'm new to Concerto but I like the idea of visualizing a contract while coding it in real time. I read the concepts of Concerto modelling [here](https://docs.accordproject.org/docs/model-concerto.html). As per my understanding, following are the points I gathered about the project: 
 
- Create an online web editor to code out the contract in the Concerto modelling language.
- Parse the code for concepts, enumerations, properties, relationships, decorators.
- Use the parsed data to create the model diagram simultaneously.

#### Example
![asd](https://user-images.githubusercontent.com/40923324/75068963-34b2dc80-5516-11ea-91d6-ff92e499ad3b.PNG)

This data model was created from the contract code given [here](https://models.accordproject.org/trademark/trademark.html) 

Some other options that can be provided are : 
- importing local contract file
- downloading the contract 
- usage of contract file from an online link
- language references

Please let me know if I'm missing out something or have got something wrong. 
PS: made this issue here, because couldn't receive an invite into Slack

**Comment by irmerk** [comment]
Great to see this! Our slack portal is [here](https://accord-project-slack-signup.herokuapp.com/), and we have a #gsoc channel. I think @mttrbrts, @jeromesimeon, and @dselman will be great resources as well regarding Concerto specifically, and @DianaLease and I will be resource overlaps with front-end work. 

I would think to get really familiar with Accord Project templates and models and how to build them by hand, and how they relate to one another.

**Comment by ankingcodes** [comment]
> I would think to get really familiar with Accord Project templates and models and how to build them by hand, and how they relate to one another.

@irmerk  Agreed ! I have started to draw some models by hand by following the source code at Accord Project Model Repository.

**Comment by ankingcodes** [comment]
@irmerk I spent some time understanding `jdl-studio`, seems like they used [`nomnoml`](http://www.nomnoml.com/) for making the UML diagram on a canvas. 
Then I checked out PlantUML's website, where I tried to convert a `concerto` model code into `UML` and pasted it on their editor. It was able to create an accurate UML diagram for the code.
So, I'd reiterate some points I'd previously discussed.
> Create an online web editor to code out the contract in the Concerto modelling language.
1.  This can be done by supporting nomnoml in Concerto, or we can use `monaco-editor` to just write the code.
> Parse the code for concepts, enumerations, properties, relationships, decorators.
2. In this step, we would use Concerto-tools to convert concerto code to uml form. 
3. Use the UML form code to create the UML diagram, something like either nomnoml or [plant-uml server](http://www.plantuml.com/plantuml/uml/jPHFRnCn4CNl-HG-Wg3v15NLa082YGijlI0EK_kn67azoyouKlZptM71gXGdu0GfjyreF7xlDy-vL2EnCgQ5JwJgM8ObUSyI9k7FyBRqb903oN9TFzOyJfoHpPsVkqUhfuC0-R6xk73V5iwv9-xQ9ER1bHWMFnP73Jmx-twnHy8TAPOhLLXVvRiSlnGSgF7z1qTco05eofx74Td-LA_8S1D7k61gD4vRDba6ol4hf9aW-AL3xTh8YaAtqKXgq7HSD63wAFkWti8NcTKSnOhy9ynWjEL5Xe4bDaP_gxZPJBjuiv4tRVXw0Hd2reW0zH8dYvoRxaHgRpZ4Zn7roAji621kaiWIRREpaaJMzkgyf-onTQcMSIJPD4lg46ptrDzhVqktgqGoTbuQpJqhNn4zrEk-QextXLuxf8lG_Ck5-h5DJZ21x7XkrTC9Cdtx_7v_ZjjdZ1p-Oh5fVMXynfn0sKLTfNH5DLelmMjc2J6JGTq0tiAHsDUXJGwLY_W6lmbbdKYG_MRdJc_n7ZFMhlcAjP_QOxY-4E2kwEO0j6eajWzuKwjzBUtgiIVa12_jDHV9b7OjLacTSwS1VyE1kz0zZrE2eKKS2lwPyWFJs_otGZoohUkTXqMR0tSepaR_1-4bSYXZMlm4)

This [website](https://plantuml.com/) shows a demo which resembles our work.
I think I'm going in right direction. Please share your suggestions.

**Comment by DianaLease** [comment]
> Then I checked out PlantUML's website, where I tried to convert a `concerto` model code into `UML` and pasted it on their editor. It was able to create an accurate UML diagram for the code.

Do you have the UML you pasted or a screenshot of this? I'd be curious to see it. Thanks!

**Comment by ankingcodes** [comment]
@DianaLease Thanks for your interest. The UML code and diagram can be found [here](http://www.plantuml.com/plantuml/uml/jPHFRnCn4CNl-HG-Wg3v15NLa082YGijlI0EK_kn67azoyouKlZptM71gXGdu0GfjyreF7xlDy-vL2EnCgQ5JwJgM8ObUSyI9k7FyBRqb903oN9TFzOyJfoHpPsVkqUhfuC0-R6xk73V5iwv9-xQ9ER1bHWMFnP73Jmx-twnHy8TAPOhLLXVvRiSlnGSgF7z1qTco05eofx74Td-LA_8S1D7k61gD4vRDba6ol4hf9aW-AL3xTh8YaAtqKXgq7HSD63wAFkWti8NcTKSnOhy9ynWjEL5Xe4bDaP_gxZPJBjuiv4tRVXw0Hd2reW0zH8dYvoRxaHgRpZ4Zn7roAji621kaiWIRREpaaJMzkgyf-onTQcMSIJPD4lg46ptrDzhVqktgqGoTbuQpJqhNn4zrEk-QextXLuxf8lG_Ck5-h5DJZ21x7XkrTC9Cdtx_7v_ZjjdZ1p-Oh5fVMXynfn0sKLTfNH5DLelmMjc2J6JGTq0tiAHsDUXJGwLY_W6lmbbdKYG_MRdJc_n7ZFMhlcAjP_QOxY-4E2kwEO0j6eajWzuKwjzBUtgiIVa12_jDHV9b7OjLacTSwS1VyE1kz0zZrE2eKKS2lwPyWFJs_otGZoohUkTXqMR0tSepaR_1-4bSYXZMlm4)

Also see [here](https://plantuml.com/) and try to copy the code there for an instant preview, just as we want in our project 👍

**Comment by jeromesimeon** [comment]
@ankingcodes I'm confused by this issue.

1. UML diagram generations already supported (`concerto compile --target PlantUML`) and this feature is already used to generate diagram in the models library https://models.accordproject.org
2. I thought the proposed project in https://github.com/accordproject/techdocs/wiki/Google-Summer-of-Code#concerto-model-web-editor was about allowing to edit the model in a graphical form. Would your suggestion allow that?

**Comment by ankingcodes** [comment]
>UML diagram generations already supported (concerto compile --target PlantUML)

@jeromesimeon Thanks for this. 

> about allowing to edit the model in a graphical form.

Yes, I agree to that. As far as I understood the project, it would be a developer/user writing a model in Concerto which will dynamically generate a diagram. As a example of this, I had shared links to the PlantUML website. specifically [this](https://plantuml.com/) where at the bottom you'd find an editor and a diagram. I'd encourage you to paste some UML code and playing around with it, you'd find that the diagram is generated  dynamically, a similar functionality we want.

So, what I thought for the project was: 
- User writes a concerto code for a model on a code editor (such as Monaco Editor)
- The concerto code is translated to UML code. `onChange` on the code editor 
- The UML is given as source to a component that generates the diagram on a canvas element.

Also, if this issue was created at the wrong place. please let me know. ( I think that way, since its an UI issue, maybe concerto-ui would be a better place )

**Comment by jeromesimeon** [comment]
> > UML diagram generations already supported (concerto compile --target PlantUML)
> 
> @jeromesimeon Thanks for this.
> 
> > about allowing to edit the model in a graphical form.
> 
> Yes, I agree to that. As far as I understood the project, it would be a developer/user writing a model in Concerto which will dynamically generate a diagram. As an example of this, I had shared links to the PlantUML website. specifically [this](https://plantuml.com/) where at the bottom you'd find an editor and a diagram. I'd encourage you to paste some UML code and playing around with it, you'd find that the diagram is generated dynamically, a similar functionality we want.
> 

Are we talking about this proposed project? https://github.com/accordproject/techdocs/wiki/Google-Summer-of-Code#concerto-model-web-editor

Maybe I'm wrong, but I was understanding the project as being the other way around: the user edits the graphical representation, and the system generates a model file (`.cto`) from it.

I agree the project description is subject to interpretation about that. Maybe @irmerk or @DianaLease can comment?

Note that if the context is Google Summer of Code, the project proposals are not limited to the idea list.

**Comment by dselman** [comment]
> Maybe I'm wrong, but I was understanding the project as being the other way around: the user edits the graphical representation, and the system generates a model file (`.cto`) from it.

You are correct - we are trying to reduce the barrier to entry for people creating Concerto models by providing a more guided graphical user experience, so they don't have to learn the textual syntax as a first step.

My ideal editor would have the text and the diagram synchronised, with the user able to edit either...

**Comment by ankingcodes** [comment]
> Are we talking about this proposed project?

@jeromesimeon  Yes. 

>  I was understanding the project as being the other way around: the user edits the graphical representation, and the system generates a model file (.cto) from it.

@irmerk and @DianaLease had given an example of jdl-studio ([see here](https://www.jhipster.tech/jdl-studio/)) in the proposal, so I didn't make an assumption of this reverse feature you've mentioned. 

> My ideal editor would have the text and the diagram synchronised,

@dselman I'd think that relates to jdl-studio 

> You are correct - we are trying to reduce the barrier to entry for people creating Concerto models by providing a more guided graphical user experience, so they don't have to learn the textual syntax as a first step. 

So that means that an user should be allowed to modify a diagram in anyway possible and also the code should change/ be generated in that way.

**Comment by dselman** [comment]
> So that means that an user should be allowed to modify a diagram in anyway possible and also the code should change/ be generated in that way.

Some core graphical actions might be:
- Add a new class (concept, transaction, asset, participant, event)
- Add a field to an existing class (including arrays)
- Add a relationship from one class to another (subclassing, or a named relationship)

Yes, you can see these equivalents in JDL Studio, and I think something similar for Concerto would be valuable.

**Comment by ankingcodes** [comment]
@dselman  I think jdl-studio takes up a code and draws the corresponding diagram on a canvas element. I dont think they allow users to directly edit the diagram on the canvas element. Am I getting something wrong ?

**Comment by ankingcodes** [comment]
I'll try to make a small prototype & I'll share with you all, and then let's discuss more on this.

**Comment by ankingcodes** [comment]
@irmerk @DianaLease @jeromesimeon After the zoomcall today, I did some thinking about how this project would be useful for end users, especially, since tools of Accord Project are used by people with legal backgrounds. So, for the project, I thought of giving option to user to act as either a developer / a non-developer, according to which the web editor would have a different layout which is as follows : 
![Dev (1)](https://user-images.githubusercontent.com/40923324/76004214-28277e80-5f2f-11ea-81f8-17a35f080402.jpg)
For the non-developer scenario, user would have a generate button which would generate the code based on inputs from the diagram created at the drag/drop canvas.
Let me know what you all think about this idea ? 
I'm currently working to build a prototype for the developer scenario, which I'd share soon.

**Comment by DianaLease** [comment]
@ankingcodes Yes, this is definitely on the right track! I wonder if instead of having two separate layouts, if the user could edit the code _or_ the diagram on one page and the other side would update accordingly. Just a thought though, this is great!

**Comment by ankingcodes** [comment]
>  I wonder if instead of having two separate layouts, if the user could edit the code or the diagram on one page and the other side would update accordingly. 

@DianaLease The second part of editing the diagram and updating the code seemed rather challenging, but that's a great suggestion and I'll definitely think more on it. 

The idea is getting inputs such as class name, properties belonging to a certain class and using that data to automatically write code (in concerto schema language) on a code editor component (for example, monaco editor). I'd be glad if other developers have some ideas on this, and would like to share.

**Comment by irmerk** [comment]
I like this idea. These mockups make me think of [sankey diagrams](http://sankeymatic.com/build/) and [flowchart generators](https://www.draw.io/). My thought on this is that this concept starts with a non-developer. So a future feature could be a developer writing code and generating a diagram.

But this starts with the non-developer, because there are already tools that developers can likely use to make a diagram, that should be an afterthought. How does a non-dev user interact with a drag-and-drop diagram which spits out the code of what they built which could be shared with a developer?

**Comment by ankingcodes** [comment]
>  How does a non-dev user interact with a drag-and-drop diagram which spits out the code of what they built which could be shared with a developer?

@irmerk I don't fully understand what you meant by this. But I think you're reiterating the point @DianaLease mentioned. 
Generating code simultaneously whilst creating the diagram is something that I cannot find a solution to right now, though I am researching on it (perhaps, @jeromesimeon and @dselman can give me some ideas on it), I have a work-around that might satisfy the issue. 
How about after a non-dev creates the diagram and generates the code, we present the option to switch to scenario 1 and edit the code as a dev ?

**Comment by dselman** [comment]
I'd approach:
1. Find a React compatible graphical editor (boxes, arrows, custom styling, drag, layout ....)
2. Use the editor to edit a diagram model (JSON data structure that represents the model)
3. Write code to convert the diagram model (JSON) to a Concerto text file
4. Write code to convert a Concerto model (use the Concerto ModelManager APIs) to a diagram model

By combining 1-4 you should be able to create a React editor that can both create CTO models, and can load CTO models for editing and save back to CTO.

**Comment by dselman** [comment]
Here is the Concerto meta-models (ie. using Concerto to describe the structure of a Concerto model):
https://models.accordproject.org/concerto/metamodel.html

**Comment by dselman** [comment]
E.g. https://github.com/projectstorm/react-diagrams
(there are probably many others)

**Comment by Anubhavshakya** [comment]
I have read the whole discussion. After that I conclude that in the summer we are going to built a web class diagram editor for non-developer. please correct me if I'm wrong.
If I'm wrong in that case we have to work on both editor for developer and non-developer then we can give the option to the user to select which type of editor he/she want. We can use this prototype for the landing page of editor.

![Homepage-2x](https://user-images.githubusercontent.com/38704248/76086482-28c91f00-5fda-11ea-961b-83b9a333aa6e.png)

As we have jdl-studio. But I found a another editor [Mermaid Live Editor](https://mermaid-js.github.io/mermaid-live-editor) that is totally based on [mermaid](https://github.com/mermaid-js/mermaid) we can use this as a reference.

**Comment by ankingcodes** [comment]
@dselman thanks for your suggestion. I was stuck on what should be used as the intermediate data structure but your comment (JSON) cleared that out for me. 
> Write code to convert the diagram model (JSON) to a Concerto text file

I believe there is code already written for doing this or the reverse of this ?

**Comment by ankingcodes** [comment]
@Anubhavshakya Thanks for your interest ! But according to the discussions that have taken place recently, this project requires to create a single component that would be usable both to the developer and the non developer.

**Comment by jeromesimeon** [comment]
@Anubhavshakya I think @ankingcodes is correct. Developers can already use VSCode, or their favourite editors to create models (and do so on a regular basis). I think the main goal here is: what if someone isn't a developer, can they still design a model (and how?).

**Comment by Anubhavshakya** [comment]
@ankingcodes Thanks for your reaction. I know that the project requires a single component. At that time I was thinking that developers and non-developers should have different user interfaces.
@jeromesimeon Yes, the main goal of this project is to develop a web editor. By using editor non-developer can also create the model.
And sorry for the late response because of the Exam.

**Comment by ankingcodes** [comment]
Since I'm done with discussion regarding the project, I'm closing this issue here.
