### ISSUE TITLE
Instance Generation should provide Regex compatible values for fields

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/concerto#171]
**Is your feature request related to a problem? Please describe.**
When generating a JSON instance for a model with fields that have regex constraints, the generated instances are not valid instances of the model.

**Describe the solution you'd like**
We should use a library such as https://github.com/fent/randexp.js, to safely create sample values that are compatible with regex annotations on models.

This will allow upstream tools (such as concerto-ui) to generate values that are valid instances of the model

**Comment by jeromesimeon** [comment]
@mttrbrts Is this issue closed by #178 ?

**Comment by mttrbrts** [comment]
Yes, thank you!
