### ISSUE TITLE
Customize the path for log files directory with environmental variable

### ISSUE THREAD

**Issue by frbrkoala** [accordproject/concerto#183]
**Is your feature request related to a problem? Please describe.**
It is currently not possible to run concerto in a runtime with limited access to the file system, like in Amazon Lambda, where write permissions are allowed only inside the `/tmp` folder.

**Describe the solution you'd like**
I would like to introduce a new environment variable called `CONCERTO_LOG_FOLDER_PATH` to specify where `@accordproject/concerto-core/lib/logger.js` will create `log` folder.

**Describe alternatives you've considered**
None

**Additional context**
This modification is needed to make concerto compatible with Amazon Lambda function on AWS cloud.

**Comment by mttrbrts** [comment]
Hi @frbrkoala , thanks for opening this. We recently did a major refactor of the way that logging works in preparation for Concerto v1.0 (https://github.com/accordproject/concerto/pull/175).

In this release, we will no longer write log files to disk at all, and you will be able to add custom loggers.

If this addresses your problem, please close this issue

**Comment by mttrbrts** [comment]
Sorry, I now see your PR. I've approved it and it will get released soon, however, please beware that given the refactor above, this behaviour will change when we release Concerto 1.0.
