### ISSUE TITLE
Numeric type Improvements

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/concerto#189]
The specification for Concerto has Integer (32bits) and Long (64bits): https://docs.accordproject.org/docs/model-properties.html#primitive-types

The current implementation supports neither. Integer and Long are treated interchangeably and internally represented as JavaScript numbers. Those are safe only up to [MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER) which is 2^53-1 instead of 2^31-1 or 2^63-1.

### Questions

- Should we try and implement this specification.
- Should we revise this, replace by a notion of big integer (then leave the behaviour to implementation -- this could be using the new big int for recent javascript implementations, be listed as safe only up to a MAX_SAFE number for some platforms?).
- Should we extend support to decimal numbers (or should we implement those on top of a big int?). Usecase: monetary amounts.

**Comment by OmkarAcharekar** [comment]
Hey @jeromesimeon, There are a number of approaches to implementing  Integer, Long.. Really, i would be looking at the Knuth algorithms. If I was being very naive and disinterested in performance, I would write the bit level algorithms directly. But they really would require lots of testing...

**Comment by dselman** [comment]
This is a nice description of how Avro deals with this: https://github.com/apache/avro/blob/master/lang/js/doc/Advanced-usage.md
