### ISSUE TITLE
Username typed incorrectly in MAINTAINERS.md

### ISSUE THREAD

**Issue by SGeetansh** [accordproject/concerto#194]
In the file MAINTAINERS.md, the GitHub username of the maintainers is typed incorrectly. It is typed as:

- Matt Roberts (dselman)
- Daniel Selman (dselman)
- Jerome Simeon (dselman)

Instead, it should be:
- Matt Roberts (mttrbrts)
- Daniel Selman (dselman)
- Jerome Simeon (jeromesimeon)

**Comment by dselman** [comment]
Fixed. Thanks!
