### ISSUE TITLE
Inconsistent support for empty identifiers

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/concerto#248]
### Description

Part of the code hints at support for empty identifiers:
https://github.com/accordproject/concerto/blob/c2ecad3e5d52b0e8b1c7caf026d62abbf4f68b6f/packages/concerto-core/lib/factory.js#L72

But other parts hint at disallowing it:
https://github.com/accordproject/concerto/blob/c2ecad3e5d52b0e8b1c7caf026d62abbf4f68b6f/packages/concerto-core/lib/serializer/resourcevalidator.js#L160

We should test it, maybe decide if we want to keep this feature or not. I'm unclear of the usecase for this.

**Comment by dselman** [comment]
I think we can disallow empty IDs. I don't remember why this was supported. I don't believe we rely on this anywhere.
