### ISSUE TITLE
Union Types

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/concerto#292]
# Feature Request 🛍️

Proposed syntax
```
concept A {
  o Integer | String value
}
``` 

This would allow new types to be created by composition rather than extension. Sometimes, this a more natural way to model business concepts. See the first example here
https://flow.org/en/docs/types/unions/#toc-disjoint-unions

**Comment by mttrbrts** [comment]
We could also consider disjointed unions, https://jsontypedef.com/docs/jtd-in-5-minutes/#discriminator-schemas

**Comment by jeromesimeon** [comment]
This is a majorly different type system (i.e., switching from OO-style to ensemblist). This will notably make a strongly typed language like Ergo on top of Concerto close to impossible (or very hard).

I would vote against supporting that feature.

A possible alternative type system with a form of union could leverage enums. E.g., see in Swift:https://docs.swift.org/swift-book/LanguageGuide/Enumerations.html

Syntax:

```
concept RGB {
  o Integer R
  o Integer G
  o Integer B
}

enum Color {
  o red
  o green
  o blue
  o String name
  o RGB rgb
```

**Comment by jeromesimeon** [comment]
With the source example in mind:

```
enum IntOrString {
  o Integer int
  o String string
}
concept A {
  o IntOrString value
}
```

**Comment by Rishabhraghwendra18** [comment]
Hello everyone . First timer this side . I want to contribute to accordproject , so is the discussion currently going or may I can get this issue to work ?

**Comment by jeromesimeon** [comment]
hi @Rishabhraghwendra18 welcome. This is very much on-going. I don't think we have decided we should do this.

**Comment by mttrbrts** [comment]
Welcome @Rishabhraghwendra18 ! 

This issue doesn't have strong support right now, and should probably be closed. However, there are several issues tagged with "Good First Issue" across the organization. In Concerto, see this list, https://github.com/accordproject/concerto/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue+%3Aoctocat%3A%22

**Comment by dselman** [comment]
Reopening this, as it has been raised recently by the community - and support has been added for it to the Typescript generator: 
https://github.com/accordproject/concerto/issues/429
