### ISSUE TITLE
Update API

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/concerto#293]
# Feature Request 🛍️
Today, creating new types programmatically requires string manipulation. There is an internal AST for a Concerto definition, but it is not documented nor designed for manipulation.

## Use Case

With an update API, a user could add a new declaration to an existing model, or even build models completely from scratch (e.g. from a graphical tool)

## Possible Solution

As well as defining a public API for model manipulation, we should define a JSON DOM (similar to Cicero Mark DOM) of a model definition to allow efficient serialisation and deserialization.

Possible API signatures
```
modelFile.addConcept(name, properties, [superType]);
modelFile.updateConcept(name, [properties], [superType]);
modelFile.deleteConcept(name);
classDeclaration.addProperty(name, type, optional, validators);
classDeclaration.updateProperty(name, type, optional, validators);
classDeclaration.deleteProperty(name);
```

## Context

Changing a model definition dynamically could lead to breaking changes in client code. We could chose to reject, warn, or allow breaking changes.

**Comment by dselman** [comment]
@jeromesimeon @mttrbrts now that we have moved Concerto to the published metamodel I think we can close this.
