### ISSUE TITLE
Concept validation results in "instance undefined" error message

### ISSUE THREAD

**Issue by sstone1** [accordproject/concerto#330]
If I validate an instance of a concept, which does not have an identifier, then the error message is wrong: `Instance undefined missing required field value2`

The `undefined` is probably the identifier which doesn't exist?

**Comment by OmkarAcharekar** [comment]
Hey, @sstone1 , I would like to work on this issue. Can you please assign this to me and explain little bit more about this issue?

**Comment by dhruv-joshi-7** [comment]
@OmkarAcharekar have you started working on this issue? If yes, can you share what have you done so far so that even I can contribute in solving this issue.

**Comment by tech-bash** [comment]
@dselman  sir, I think so its not a bug.
