### ISSUE TITLE
TypeScript generation and validation issue for types with dates

### ISSUE THREAD

**Issue by sstone1** [accordproject/concerto#331]
I've got more TypeScript fun!

The following model:
```
concept ExampleEventOutputMetadata {
  o DateTime timestamp
}
```

... generates the following TypeScript:

```
export interface IExampleEventOutputMetadata extends IConcept {
   timestamp: Date;
}
```

... so I set the timestamp field to `new Date()`.

However, `Concerto.validate()` rejects such an object with a validation error. It seems to be expecting a string value for `timestamp`, as when I override the TypeScript code to set the `timestamp` field to an ISO date string, it works fine.

**Comment by Krish-bhardwaj** [comment]
Hey, @sstone1  I would like to work on this issue since I'm new to opensource i don't know from where to start. Can you please assign this to me as I have to get started 

Thanks in advance : )

**Comment by arpit-maurya** [comment]
@sstone1 @DianaLease @dselman Please anybody can give me a more detail of this Issues, am interested to solve this issue
