### ISSUE TITLE
MetaModel: Support for exporting full ModelManager (several related CTO models)

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/concerto#339]
# Feature Request 🛍️

Current MetaModel only supports converting between a single CTO file or ModelFile object and the MetaModel. Names can be resolved if a model manager is passed as well. It would be useful to allow conversion between a set of related CTO files or a full ModelManager and the MetaModel.

## Use Case

- This would allow to have full type information for a model, including its imports, making the MetaModel stand-alone.

## Possible Solution

- Add a new top-level notion of `concerto.metamodel.Models` containing an array of `concerto.metamodel.Model` for each CTO file.
- Add conversion between `concerto.metamodel.Models` and `ModelManager`
- Add corresponding CLI support

**Comment by jeromesimeon** [comment]
Preliminary support for this available in #338 with the new Concerto Metamodel version `0.3`.

**Comment by Jeevan-Kiran-Lenka** [comment]
Hey! @jeromesimeon I would like to know more about this `feature-request`, and then to solve this. I would love if you can assign this to me, and give a starting point for this feature-requerst :)
