### ISSUE TITLE
Update parser to align with meta model

### ISSUE THREAD

**Issue by dselman** [accordproject/concerto#344]
# Feature Request 🛍️
If the output from the parser was metamodel JSON then it might simplify the code, and allow the CTO -> metamodel code (which use the large parser.js file, generated via Peggy) to be moved into its own package.

## Use Case
Code simplification. Reduce bundle size for people that don't need to populate ModelManager from CTO text.

## Possible Solution
I've made a start at refactoring the parser. See attached. To continue this work we also need to update the various introspect classes to be populated from the metamodel.

[parser.pegjs.txt](https://github.com/accordproject/concerto/files/7468678/parser.pegjs.txt)
.

**Comment by dselman** [comment]
@jeromesimeon can we close this now?

**Comment by jeromesimeon** [comment]
@dselman indeed we can! the latest parser now generates instances of the meta model. See #350
