### ISSUE TITLE
Concerto throws an error when importing local files (solved when importing from web url)

### ISSUE THREAD

**Issue by OliverTod** [accordproject/concerto#351]
I get the following namespace error when I try and use a concerto CLI command (eg concerto compile) on a model file that imports external models from a local file (contained in the same directory).
![image](https://user-images.githubusercontent.com/73812545/142565543-416c808e-a4ed-4a7f-9df7-aac48b4d4599.png)

I didn't get this issue after I uploaded the cto files to a web server and used the 'from' syntax.
![image](https://user-images.githubusercontent.com/73812545/142565623-c9e806bf-61a2-40ab-b580-f0dfda11eb4b.png)

Any idea what might be happening here? It's likely to be user error, but I can't figure it out.

Thanks in advance

**Comment by dselman** [comment]
The `--model` argument accepts an array of file names, so if you have imports across several files you will need to pass them all into the `--model` argument.

**Comment by OliverTod** [comment]
Hi @dselman, any chance you could help me figure out the syntax for that? Perhaps it would be helpful for others if we put the syntax in the documentation.
