### ISSUE TITLE
Minor Typographic Error

### ISSUE THREAD

**Issue by AbhijithGanesh** [accordproject/concerto#372]
# Bug Report 🐛
Incorrect spelling of `discord`

Instead of `discord` it has been typed as `dsicord`
## Expected Behavior
Ideally the correct spelling should've been mentioned

## Context (Environment)
Documentation

### Desktop
 - OS: [e.g. windows]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 0.22.15]

**Comment by Jeevan-Kiran-Lenka** [comment]
I guess this issue has been solved?

**Comment by jeromesimeon** [comment]
I can't find a record of this:

```
zsh-5.8$ grep -r dsicord .
zsh-5.8$ 
```

I'm closing.
