### ISSUE TITLE
Decorator Validation

### ISSUE THREAD

**Issue by dselman** [accordproject/concerto#391]
# Feature Request 🛍️

The current decorator support in Concerto has some issues which were deferred initially due to time constraints.
1. Decorators are not modelled types, rather they have a generic structure
2. Decorators cannot be defined within a namespace and imported / shared 

## Use Case

Allow users to define sets of decorators and to import and share them. Ensure that decorator arguments are specified and valid.

## Possible Solution

Define a root decorator concept that decorator definitions must extend.

Abstract decorator concept is added to the root (system) namespace:

```
namespace concerto.decorator@1.0.0

abstract concept Decorator {}
```

Users may specialise the decorator in their own namespaces:

```
namespace org.acme.decorators@1.0.0

import concerto.decorator@1.0.0.{Decorator}

concept Hide extends Decorator {
   o Boolean visibility
   o String docs optional
}
```

Users may use the defined decorator in their own namespaces:

```
namespace org.acme.person@1.0.0

import org.acme.decorators@1.0.0.{Hide}

concept Person {
   @Hide
   o String ssn
}
```

This declares a decorator called `Hide` that takes a single Boolean argument (the name of the property is ignored).

Update the `Decorator.validate`method to optionally validate all the decorators on namespaces/declarations/properties.
- Decorator names and imports are validated
- Decorator arguments are validated

## Context

Have a need for a rich set of decorators that can be managed over time.

## Detailed Description

The proposed change would NOT impact the Concerto parser or metamodel or break code generation.

**Comment by sanketshevkar** [comment]
@mttrbrts I'd like start with design for this. What would be the priority of this feature for the community?

**Comment by dselman** [comment]
Some notes:
1. We need to support validating decorators that are defined, or ignoring undefined decorators.
2. We need ignore, warning and error as log levels for decorator validation

E.g. I may choose to use:
```
defined: error
undefined: warning
```

Meaning that if a decorator has been defined, then using it incorrectly is an error, whilst if I use an undefined decorator, that would be a warning.

Default config would be:

```
<empty>
```
Meaning that there is no defined behavior for defined decorators, or undefined decorators.

It was also decided that decorators must be imported into the namespaces where they are used, and that these imports are validated.

All this should also work with Decorator Command Sets — we need to ensure that the imports for applied decorators are dynamically added to the models. This means that we will need a fully-qualified name, or namespace, for a decorator command.
