### ISSUE TITLE
Concerto vNext Proposals

### ISSUE THREAD

**Issue by dselman** [accordproject/concerto#420]
# Feature Request 🛍️

These are ideas, open for discussion.

## 1. Faceted Primitive Types #433 - 3.x

```
typedef SSN = String regex=/\d+/

concept Person {
  o SSN ssn
}
```

References: 
- https://www.w3schools.com/xml/schema_facets.asp
- https://docstore.mik.ua/orelly/xml/schema/ch05_01.htm

## 2. Reimplement in Typescript #406 - 4.x (or possibly 3.x if we don't use mm classes)

Generate TS code from the metamodel (bootstrap) and then code the implementation against the generated code, ensuring consistency.

## 3. Cleaner / Simpler Functional APIs

Better separation between serialisation, introspection, validation - for example.

## 4. Final Types #482 - (3.x)

The `$class` is required in serialised instances because concepts can be extended. We could support the addition of a `final` keyword which would indicate that a concept could *not* be extended, meaning that the type of an object can be inferred by introspecting the model.

## 4. Numeric type enhancements #189 - (4.x)

Ensure full support integer and long numeric types in the JavaScript library, perhaps by using the built-in big integer support in JavaScript. Also, should we introduce a new decimal type to handle monetary amounts?

## 5. Optional vs required property handling consistency

Martin to provide further details. 

## 6. Decorators v2 #391 - (4.x)

Introduce well defined, modelled decorators: https://github.com/accordproject/concerto/issues/391

## 7. Import Aliasing #480 - (3.x?)

Allow models to alias imports to deal with name collisions.

## 8. Improved TypeScript generation #449 - (3.x - new target?)

This generator would generate TypeScript interfaces that describe the JSON structure of the data, and TypeScript classes that can be used to parse, validate and serialize instances with the expected types.

### 9. Record Types (Dictionary / Maps) #447 - (4.x)

Allow modellers to define record types aka maps or dictionaries.

**Comment by mttrbrts** [comment]
Closing. Each of the issues are tracked separately and managed in the Roadmap.
https://github.com/orgs/accordproject/projects/15/views/1
