### ISSUE TITLE
Faceted Primitive Types

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/concerto#433]
# Feature Request 🛍️
Extend the Concerto Modelling Language and Metamodel to support faceted primitive types.

## Use Case
This feature would allow users to reuse validations or restrictions on a property, for example.

Declare:
```
namespace concerto.scalars@1.0.0

@personal
scalar SSN extends String regex=/\d{3}-\d{2}-\{4}+/ default=000-00-0000
```

Use:
```
namespace org.acme.hr@1.0.0
import concerto.scalars@1.0.0.SSN

concept Person identified by ssn {
    o SSN ssn
    o String givenName
}
```

## Possible Solution
Alternatives for the new keyword:
- `typedef`
- `facet`
- `type`
- `scalar`
- `property`
- `primitive`

## Context

Without this feature, users today are forced to redefine the same set of validations multiple times which can lead to divergence.

## Detailed Description

1. The implementation should allow all type and decorator information to be inherited.
2. The implementation should allow faceted primitive types to be imported from other models.
3. As a primitive type, faceted primitive types cannot be extended.
4. String types should be useable as identifiers

References: 
- https://www.w3schools.com/xml/schema_facets.asp
- https://docstore.mik.ua/orelly/xml/schema/ch05_01.htm
- https://www.edgedb.com/docs/datamodel/properties#abstract-properties
- https://www.edgedb.com/docs/reference/sdl/scalars#scalar-types

**Comment by Jonathan-Casey** [comment]
I'd vote for using `type` as the keyword used here, Microsoft are using this approach in some of their other languages:

https://fsharpforfunandprofit.com/posts/type-abbreviations/
https://learntypescript.dev/04/l3-type-aliases

**Comment by dselman** [comment]
Can we extend another scalar?
