### ISSUE TITLE
Concerto Printer should implement functionality for additional formats: JSONSchema, XMLSchema, OData

### ISSUE THREAD

**Issue by Jonathan-Casey** [accordproject/concerto#453]
# Feature Request 🛍️

At present, Concerto Printer provides functionality to print to `CTO` format, for example `Printer.toCTO(ast)`. This allows 'code gen' for each namespace associated in the meta-model hierarchy. 

For example, a metal-model with both a direct and a transitive dependency will have multiple namespaces (one per node in the hierarchy), and therefore we can pull multiple `AST`'s from the ModelManager, and using `Printer`, print a string representation of each `AST`, or namespace - each string being the generated `CTO` from the `AST` associated with the namespace. 

```
  public generateConcerto(mgr: ModelManager) {
    const ns = mgr.getNamespaces().filter(ns => ns !== 'concerto'); // ignore root level 'concerto' ns
    const asts = ns.map(ns => mgr.getModelFile(ns).getAst());
    // print each AST of each ns to CTO
    const cto = asts.map(ast => Printer.toCTO(ast));
    return cto;
  }
```

A current use case for this might be writing each of these strings to file, where they will be ultimately exported as a Zip archive. The end user is able to faithfully recreate a file per namespace from the meta-model using the above approach.

As demonstrated, this works great when end users want to work with the `Concerto` format, however the current functionality is limited in regard to all other supported formats (`XMLSchema`, `JSONSchema`, `OData`, `PlantUML`). 

Take a `JSONSchema` use case for example. At present, the end user can generate only a single string which contains all dependencies in the hierarchy. It is not currently possible to generate a `JSONSchema` file per namespace - there is no parity with the `Concerto` format in this respect.

One other inconsistency to note is in the code path - this is not 1:1 if generating source files for the other formats, when compared to `CTO` - as no `Printer` implementation currently exists for these other formats. The end user must make use of a `Visitor`, and pass in a `FileWriter` as a dependency. The generated code can then be retrieved from the `FileWriter`, once `Vistor.visit(...)` has traversed the `AST`.

We would ideally like to have the ability to print to each of the formats - `JSONSchema`, `XMLSchema`, `OData`, with a string representation per namespace in the model hierarchy, preferably mirroring the implementation of `Print.toCTO(...)` -- for example `Printer.toOData(...)`

## Possible Solution

Implement functions in the `Printer` class to support `JSONSchema`, `XMLSchema`, `OData`,. For example - `Printer.toOData(...)`, or possibly create a Printer per format eg. `ODataPrinter`.

**Comment by dselman** [comment]
I think I prefer to leave the format conversions in the `concerto-tools` package - and callable either via API using their Visitor, or via the `concerto` CLI. The CTO format has a special status in that it is the concrete syntax for the metamodel and is hence lossless.
