### ISSUE TITLE
Support for Mermaid UML Class Diagrams in concerto-tools

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/concerto#457]
GitHub now supports diagrams using the mermaid tool.
https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/

Natively supporting mermaid as a target language for Concerto would allow us to visualise models inside markdown files without relying on the third-party PlantUML API.
https://github.com/mermaid-js/mermaid#readme

The solution would involve writing a new MermaidVisitor that follows the pattern of the PlantUML visitor, https://github.com/accordproject/concerto/blob/master/packages/concerto-tools/lib/codegen/fromcto/plantuml/plantumlvisitor.js

The visitor should also be exposed to the CLI `compile` command.

## Example Diagram 
```
classDiagram
    Animal <|-- Duck
    Animal <|-- Fish
    Animal <|-- Zebra
    Animal : +int age
    Animal : +String gender
    Animal: +isMammal()
    Animal: +mate()
    class Duck{
      +String beakColor
      +swim()
      +quack()
    }
    class Fish{
      -int sizeInFeet
      -canEat()
    }
    class Zebra{
      +bool is_wild
      +run()
    }
```

```mermaid
classDiagram
    Animal <|-- Duck
    Animal <|-- Fish
    Animal <|-- Zebra
    Animal : +int age
    Animal : +String gender
    Animal: +isMammal()
    Animal: +mate()
    class Duck{
      +String beakColor
      +swim()
      +quack()
    }
    class Fish{
      -int sizeInFeet
      -canEat()
    }
    class Zebra{
      +bool is_wild
      +run()
    }
            
```

**Comment by dselman** [comment]
And the icing on the cake is that we *already* have the visitor!
https://github.com/accordproject/cicero-vscode-extension/blob/master/client/src/mermaidvisitor.ts

**Comment by dselman** [comment]
GitHub now supports visualising Mermaid within markdown files

https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/
