### ISSUE TITLE
Extend CLI to manage Concerto model versions

### ISSUE THREAD

**Issue by sstone1** [accordproject/concerto#465]
# Feature Request 🛍️
Now that model files can contain version numbers, we should extend the CLI so that it can be used to manage Concerto model versions.

## Use Case
I want to increase my model file version numbers when I publish my model files, or set them to a specific value without having to open up a text editor.

## Possible Solution
Do something similar to the `npm version` CLI:

`concerto version patch **/*.cto` - bump patch level of all CTO files
`concerto version major **/*.cto` - bump major level of all CTO files
`concerto version 1.2.3 **/*.cto` - set version to 1.2.3 for all CTO files

## Context

Makes it hard to implement a version management strategy for models in a CI/CD pipeline.

**Comment by dselman** [comment]
One point to bear in mind, is that we don't currently preserve code comments in the CTO files - so if you use the metamodel (AST) to bump the version number and then regenerate the CTO we will lose all the code comments. An alternative would be to parse the CTO file to check that it is valid and then make a textual update to the version of the namespace.
