### ISSUE TITLE
Reserved fields

### ISSUE THREAD

**Issue by sstone1** [accordproject/concerto#503]
# Feature Request 🛍️

Provide a feature similar to the `reserved` keyword in Protocol Buffers (https://developers.google.com/protocol-buffers/docs/proto3#reserved), allowing a model author to reserve a property name for future use, or to mark a property as deleted (but acceptable by the parser). 

## Use Case

Removing a field from a concept is a breaking change, requiring a major version bump. This feature would allow us to remove fields from concepts as a compatible change, in a minor or patch version bump. This would reduce the number of major versions that must be managed to work with data that conforms to the model. It is also not possible to reserve a property name for future use. This feature would allow us to do so.

## Possible Solution

```
concept Foo {
  o String prop1 reserved
}
```

```
concept Foo {
  x String prop1
}
```

**Comment by dselman** [comment]
Can you elaborate please, including a scenario. I'm struggling to understand how this would work?
