### ISSUE TITLE
Repository restructuring

### ISSUE THREAD

**Issue by sstone1** [accordproject/concerto#518]
We now have two implementations of Concerto, one for JavaScript runtimes (https://github.com/accordproject/concerto) and one for .NET (https://github.com/accordproject/concerto-dotnet). It is conceivable that we will have other implementations over time for other languages and runtimes.

We need to think about how we structure the codebase going forwards.

This repository is a mix of things:
1. Things that are common across all implementations, such as the metamodel definition.
2. Things that could be reimplemented in other languages, but there is no real need to do so, such as the code generation tools and CLI.
3. Things that do need to reimplemented in other languages to support application developers, such as the parsing and validation logic.

We should consider splitting 1 and 2 out into separate repositories (for example, `concerto-metamodel` and `concerto-tools`), and then consider renaming this repository (for example, `concerto-js`) to establish a pattern for all of our implementations going forwards.

We may want to consider this at the same time as https://github.com/accordproject/concerto/issues/406, as it may be easier to reimplement from scratch using TypeScript as opposed to trying to migrate all of our JavaScript code and tests.

**Comment by Jonathan-Casey** [comment]
Work to be done:

- Breaking out `concerto-cli`, `concerto-metamodel` & `concerto-tools`  to independent repositories, to enable separate release process from the other packages.  `concerto-tools` to be renamed to `concerto-codegen`.

- update project references
- ensure publish pipeline is setup and operational
- setup of github actions
- maintain git history [prune history]

**Comment by Jonathan-Casey** [comment]
New repositories created

- https://github.com/accordproject/concerto-cli
- https://github.com/accordproject/concerto-codegen
- https://github.com/accordproject/concerto-metamodel

**Comment by DianaLease** [comment]
@Jonathan-Casey can this be marked as done or is there still work needed on this?
