### ISSUE TITLE
Documentation restructuring

### ISSUE THREAD

**Issue by sstone1** [accordproject/concerto#519]
The documentation for Concerto is currently hosted in the overall Accord Project documentation: https://docs.accordproject.org/docs/accordproject.html

There's a section under "Template Guides" and a reference section for the CLI and JavaScript API.

IMO, the documentation for Concerto is difficult to find if you are only interested in Concerto - it's buried in amongst everything else around Cicero templates, and it's not clear how you can get started with just Concerto.

We should consider pulling the Concerto documentation out more, perhaps making Concerto it's own top level section or even hosting a separate Concerto documentation site.

We also need to consider how we will make the .NET API documentation available once we have that.

**Comment by dselman** [comment]
Working on this here: https://github.com/accordproject/concerto-docs
