### ISSUE TITLE
Remove FileWriter

### ISSUE THREAD

**Issue by dselman** [accordproject/concerto#54]
It would be great to move FileWriter into its own or another module (concerto-tools?). It depends on `mkdirp` which drags in `minimist`.

**Comment by gahag** [comment]
Can I work on this to move FileWriter to codegen in concerto-tools?

**Comment by jeromesimeon** [comment]
I'm unclear whether we should remove `FileWriter` now that we have code in `concerto-core` to resolve external models and drop them to disk, unless we feel like moving that functionality entirely in a different place e.g., `concerto-cli`.

**Comment by jeromesimeon** [comment]
FileWriter is still used in PlantUMLGenerator which is used in `parsejs.js` See #69.

**Comment by jeromesimeon** [comment]
Addressed as part of #122 pending review
