### ISSUE TITLE
Getting the same error, powershell does not recognize ergo or concerto

### ISSUE THREAD

**Issue by semihtheresearcher** [accordproject/concerto#540]
![image](https://user-images.githubusercontent.com/95018675/197380357-53c2c584-8fed-4263-b24e-17a7bc4a48f2.png)
NPM is installed

I run this command, no problem: npm i -g @accordproject/concerto-cli

then I run this command: concerto compare --old model.cto --new model-with-changes.cto 

But I'm getting aforementioned error.

C:\Users\Administrator\Desktop\work_study\VS> this path is added as a PATH variable to the system variables.

**Comment by mttrbrts** [comment]
Hi @LawyerDev68, we don't test the Concerto CLI against PowerShell unfortunately. Do you see the same behaviour for the Windows Terminal too?
