### ISSUE TITLE
Support for identifying a concept using a string scalar

### ISSUE THREAD

**Issue by dselman** [accordproject/concerto#559]
# Bug Report 🐛 or Feature?

It would be useful to be able to identify concepts using a scalar.

## Expected Behavior

Be able to reference a scalar and use it as an identifying field.

## Current Behavior

```
namespace test

enum Color {
  o RED
  o GREEN
  o BLUE
}

scalar Email extends String

@resource
concept Person identified by email {
  o Email email
  o Color color
}
```

```
IllegalModelException: Class "Person" is identified by field "email", but the type of the field is not "String". Line 12 column 1, to line 16 column 2. 
```

## Steps to Reproduce

1.
2.
3.
4.

### Desktop
 - OS: [e.g. macOS]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 0.22.15]

**Comment by mttrbrts** [comment]
Example updated.
