### ISSUE TITLE
Move the Concerto documentation into the AP documentation site

### ISSUE THREAD

**Issue by dselman** [accordproject/concerto#56]
We should move the documentation for the CTO file format, runtime etc into the AP technical docs for publication and management:
https://github.com/accordproject/techdocs

Generate the JSDoc API docs and integrate into the technical docs.

- [x] Move README documentation to techdocs
- [x] generate JSDoc API in techdocs
- [ ] Review material from https://docs.accordproject.org/docs/next/model-concerto.html that could be used in techdocs

**Comment by irmerk** [comment]
## Hacktoberfest:
This issue can provide for multiple pull requests.

**Comment by christyjacob4** [comment]
Can I work on this @irmerk @dselman

**Comment by christyjacob4** [comment]
Hey @irmerk  Can you please help me get started?

**Comment by irmerk** [comment]
I would be following through the [releases](https://github.com/accordproject/concerto/releases) as well as some of the issues tracking documentation for the overall `v0.20` release propagation:

https://github.com/accordproject/concerto/issues/64
https://github.com/accordproject/techdocs/issues/111
https://github.com/accordproject/techdocs/issues/108
https://github.com/accordproject/techdocs/issues/87

**Comment by christyjacob4** [comment]
Just to clarify, I'd have to add a section to this called Concerto?
![test](https://user-images.githubusercontent.com/20852629/66135529-b9f52d80-e617-11e9-98b3-bcb1f85144bf.png)

**Comment by irmerk** [comment]
Unsure, I think we'd need more input from @jeromesimeon, @dselman, @mttrbrts, and @4katie.

So far my thoughts are having more information [here](https://docs.accordproject.org/docs/next/model-concerto.html)

**Comment by christyjacob4** [comment]
Okay sure @irmerk . What do you suggest I do in the mean time?

**Comment by irmerk** [comment]
I'm opening this back up as being stale.

@christyjacob4 like I said I think joining those would help with issues like this one.

**Comment by jeromesimeon** [comment]
`README` material has been moved to https://docs.accordproject.org/docs/next/model-concerto.html

**Comment by jeromesimeon** [comment]
Documentation for Concerto has been moved to : https://docs.accordproject.org/docs/model-concerto.html

Requests for improvements or fixes can be open as new issues directly on the documentation repo.
