### ISSUE TITLE
Update published metamodel

### ISSUE THREAD

**Issue by dselman** [accordproject/concerto#567]
# Bug Report 🐛

The published Concerto metamodel is missing Scalars.
https://models.accordproject.org/concerto/metamodel@0.4.0.html

## Expected Behavior

The published metamodel should be in sync with the code.

## Steps to Reproduce

1.
2.
3.
4.

### Desktop
 - OS: [e.g. macOS]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 0.22.15]

**Comment by sstone1** [comment]
See also: https://github.com/accordproject/concerto/issues/556

**Comment by Pushkarmondal** [comment]
can you please tell me about the problem?

**Comment by mttrbrts** [comment]
@Pushkarmondal The metamodel definition from the `concerto-metamodel` package should be extracted and published to the [accordproject/models](https://github.com/accordproject/models) repository
