### ISSUE TITLE
Identifier Regex is too restrictive.

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/concerto#572]
# Bug Report 🐛
As originally reported by @DS-AdamMilazzo.

Regarding the regex for a valid Concerto field name in the JSON representation of a model:

```regex
^(?!null|true|false)(\p{Lu}|\p{Ll}|\p{Lt}|\p{Lm}|\p{Lo}|\p{Nl}|\$||\\u[0-9A-Fa-f]{4})(?:\p{Lu}|\p{Ll}|\p{Lt}|\p{Lm}|\p{Lo}|\p{Nl}|\$||\\u[0-9A-Fa-f]{4}|\p{Mn}|\p{Mc}|\p{Nd}|\p{Pc}|\u200C|\u200D)*$
```
Is it really necessary to avoid the names "null", "true", and "false"?  There's no ambiguity between "null" and null in JSON, anyway. The only trouble may be in the Concerto language, but this regex applies to the JSON format.

**Comment by DS-AdamMilazzo** [comment]
More broadly, I think that Concerto should enforce different formats in different contexts. First of all, I'll note that the Concerto metamodel (where these regexes are defined) is supposed to be for the JSON format and not the Concerto (.cto) format, which may well have different rules.

1. **Field names and enum values** - There should be no restrictions whatsoever in my opinion. Any legal JSON property name or string should be a legal field name or enum value in Concerto, except maybe empty strings if they're too hard to support.
2. **Type names (concepts, etc)** - I think these should be restricted. In fact, I would restrict them even more than you do above. I would not allow arbitrary characters via escaping. The usual `^[_A-Za-z][_0-9A-Za-z]*$` format should be fine. As for trying to exclude certain reserved words (e.g. "concept"), I think that's okay (if done correctly) but I also think it's unnecessary.
3. **Namespace names** - I think these should also be restricted more than you currently do. You currently allow namespace names like `foo\u0020\bar`. I'd limit them to dot-separated strings where each piece has to match `^[_0-9A-Za-z]+$` (or maybe `^[_A-Za-z][_0-9A-Za-z]*$`) or something.

As for the Concerto (.cto) language, I think the \uXXXX escaping mechanism that you have today is okay (except where it doesn't fully work), but it'd be nicer if you could simply quote things, e.g. `"my value"` versus `my\u0020value`.

**Comment by mttrbrts** [comment]
## Regular Expressions

First, some definitions.

### Unicode Categories
See https://en.wikipedia.org/wiki/Unicode_character_property#General_Category for an full explanation of Unicode Categories such as `\p{Lu}`.

| Value | Category |
|--|--|
|`\p{Lu}`| Letter, uppercase |
|`\p{Ll}`| Letter, lowercase|
|`\p{Lt}`| Letter, titlecase|
|`\p{Lm}`| Letter, modifier|
|`\p{Lo}`| Letter, other|
|`\p{Nl}`| Number, letter|
|`\p{Nd}`| Number, decimal digit|
|`\p{Mn}`| Mark, non-spacing|
|`\p{Mc}`| Mark, spacing-combining|
|`\p{Pc}`| Punctuation, connector|
|`\u200C`| Zero-width non-joiner|
|`\u200D`| Zero-width joiner|

### Psuedo-JavaScript Identifier
From ECMAScript 2015, 11.6 Names and Keywords
https://262.ecma-international.org/6.0/#sec-names-and-keywords
```regexp
/^(?!null|true|false)(\p{Lu}|\p{Ll}|\p{Lt}|\p{Lm}|\p{Lo}|\p{Nl}|\$|_|\\u[0-9A-Fa-f]{4})(?:\p{Lu}|\p{Ll}|\p{Lt}|\p{Lm}|\p{Lo}|\p{Nl}|\$||\\u[0-9A-Fa-f]{4}|\p{Mn}|\p{Mc}|\p{Nd}|\p{Pc}|\u200C|\u200D)*$/
```
> Note 1. This expression does not exclude keywords such as `while`, `for` which are prohibited in ECMAScript 2015.

> Note 2. Concerto does not use this expression directly because negative lookaheads permit dangerous expressions (ReDOS). Instead reserved words are prevented in the API. 

### JSON String
From ECMA-404, 2nd Edition. As used in String keys and values in JSON objects.
```regexp
/"([^"\\\u0000\u001f]*|\\["\\bfnrt\/]|\\u[0-9a-f]{4})*"/i
```

### JavaScript Identifiers, allowing keywords

This option does not prevent the use of language keywords (such as `true`, `null`, `while` etc.). This would force all code generation logic to escape/unescape identifiers for the relevant target language.

```regexp
/^(\p{Lu}|\p{Ll}|\p{Lt}|\p{Lm}|\p{Lo}|\p{Nl}|\$|_|\\u[0-9A-Fa-f]{4})(?:\p{Lu}|\p{Ll}|\p{Lt}|\p{Lm}|\p{Lo}|\p{Nl}|\$|\\u[0-9A-Fa-f]{4}|\p{Mn}|\p{Mc}|\p{Nd}|\p{Pc}|\u200C|\u200D)*$/
```

## Comparison

Definitions for cell values are defined above.

| Identifier Type | CTO Pattern | AST Pattern† | Proposed CTO Pattern | Proposal is backwards compatible CTO |
|---|---|---|---|---|
| Property Names | Psuedo-JavaScript Identifier | JSON String | JavaScript Identifiers, allowing keywords | Yes |
| Enumeration Names‡ | Psuedo-JavaScript Identifier | JSON String | JavaScript Identifiers, allowing keywords | Yes |
| Declaration Names<br />(Concepts, Enums, Scalars) | Psuedo-JavaScript Identifier | JSON String | JavaScript Identifiers, allowing keywords | Yes |
| Namespaces Part* | Psuedo-JavaScript Identifier | JSON String | JavaScript Identifiers, allowing keywords | Yes |


> *All Namespaces are period-separated and terminated by an optional version expression, e.g. `@1.2.3-alpha.4`

> †Although the Concerto metamodel defines these constraints on identifier fields in the AST, they are not enforced today.

> ‡Concerto doesn't support enumeration values (in addition to enumeration identifiers) and so supporting JSON Strings is difficult. In TypeScript enums have optional values which as JSON Strings, we could adopt the same approach. JSON Schema also doesn't distinguish between enumeration identifiers and values, however, it implicitly allows JSON Strings (and other primitive values) as enumeration options.

**Comment by mttrbrts** [comment]
In summary, today, we only partially prevent the use of JavaScript keywords, this causes confusion to downstream users, but without full protection during code generation for TypeScript. I suggest that we relax the constraint to allow `false`, `true` and `null` as identifiers, and delegate escaping/unescaping to each code generation library in a language-specific way (our reserved keywords in Concerto, should not be the union of reserved words for all target languages).

**Comment by dselman** [comment]
This looks good @mttrbrts — I'd be in favour of enforcing the same restrictions on AST as in CTO, to ensure that we can't generate invalid CTO from AST in the CTO printer. We should add something to the Concerto docs to make these restrictions more visible.

**Comment by dselman** [comment]
As a second set of PRs perhaps we can add some utilities or conventions in how the code gen targets indicate their reserved words, and how we escape them?
