### ISSUE TITLE
Convert a payload to and from a Concerto-compliant one

### ISSUE THREAD

**Issue by stefanblaginov** [accordproject/concerto#601]
We would like to be able to convert any payload that has an existing Concerto model to a Concerto-compliant one (i.e. containing `$class` fields etc).

This already exists in an experimental version in a private repo and can be moved to `concerto-tools`.

**Comment by mttrbrts** [comment]
@stefanblaginov is this a duplicate of #542 ?

**Comment by DS-AdamMilazzo** [comment]
I don't think it's quite the same. #542 still requires `$class` fields where it would be ambiguous without them. I don't know what it means to talk about a "payload that has an existing Concerto model" that's not already "a Concerto-compliant one". Perhaps it means something like "Here's a bare JSON object. I know it doesn't say so, but it's actually a Foo@1.2.3. Now go fix it up to make it legal."? An example would help. :-)
