### ISSUE TITLE
Remove references to Ergo from Concerto

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/concerto#610]
With the [Ergo language no longer maintained](https://github.com/accordproject/technical-steering-committee/issues/35#issuecomment-1262787490) we should clean up all of the code paths that are Ergo-specific in Concerto.

This is expected to be a breaking-change because it will require removing parameters from some public API operations. However, the impact is expected to be very limited, because the only usage of those parameters is within the Ergo engine.

We could consider retaining the ordering of parameters in API operations so as not to force a new major version ahead of time. 

Examples of redundant code can be found with the following query:
https://github.com/search?q=repo%3Aaccordproject%2Fconcerto+ergo+language%3ATypeScript+OR+language%3AJavaScript&type=code&l=TypeScript

e.g.
https://github.com/accordproject/concerto/blob/2f22485b57601dd82df38a0c987379d1ad993361/packages/concerto-core/lib/serializer/jsongenerator.js#L123-L133

The clean-up should also remove redundant tests, and CLI operations.

**Comment by jamieshorten** [comment]
Please assign this to me.
