### ISSUE TITLE
Release Notes (v0.20 Project)

### ISSUE THREAD

**Issue by irmerk** [accordproject/concerto#64]
## Tasks
- This will track and construct the overall release notes for this repo in relation to the `v0.20` project
  - Will cover everything from the inception of this repo

## Related Issues:
- N/A

**Comment by jeromesimeon** [comment]
Concerto `0.81.*` is published, used in Cicero `0.20`, with release notes here: https://github.com/accordproject/concerto/releases/tag/v0.82.1

Can we close this?

**Comment by snehit31** [comment]
Can i contribute?
