### ISSUE TITLE
API to Create an English Vocabulary File for a Model

### ISSUE THREAD

**Issue by dselman** [accordproject/concerto#644]
# Feature Request 🛍️

To bootstrap the creation of a vocabulary for a model it would be useful to add an API that uses the default English missing term generator to bootstrap a vocabulary file for all concepts and properties in a model.

## Use Case

Users that would like to start using a vocabulary file need an easy path to get started.

**Comment by dselman** [comment]
Close! What I was thinking was a new code generator, so we could run it using:

```
concerto compile --model test@1.0.0.cto --target vocabulary
```

That saves creating a new CLI command etc.

The visitor for the code generator would create a voc file for each model file in the model manager.

The [English Missing Term Generator](https://github.com/accordproject/concerto/blob/main/packages/concerto-vocabulary/lib/vocabularymanager.js#L60) will allow us to populate those `# Add your definition` with a machine generated term that people can then customise.

Would you like to work on this one?

**Comment by sanketshevkar** [comment]
Yes sure.

> The [English Missing Term Generator](https://github.com/accordproject/concerto/blob/main/packages/concerto-vocabulary/lib/vocabularymanager.js#L60) will allow us to populate those # Add your definition with a machine generated term that people can then customise.

Just saw the method and edited the YAML file.

**Comment by dselman** [comment]
Great, it's all yours!

**Comment by dselman** [comment]
BTW - the English Missing Term Generator can also be applied to concept names (property name is optional).

**Comment by dselman** [comment]
Don't forget to register the new code generator here: https://github.com/accordproject/concerto-codegen/blob/main/lib/codegen/codegen.js

And add doc page here: https://github.com/accordproject/concerto-docs/tree/main/docs/reference/codegen

**Comment by sanketshevkar** [comment]
Yes, sure will keep in mind. Thank you Dan. :)

**Comment by dselman** [comment]
This may be helpful: https://concerto.accordproject.org/docs/reference/codegen/codegen-create-new

**Comment by dselman** [comment]
We must have broken vocabulary management when we added scalars. Do you want me to fix that?

**Comment by sanketshevkar** [comment]
If that's how the output should be. I can try to patch it up in the same PR?
I don't think it'll be a blocker for this particular PR. I'll investigate and let you know. If it feels like a small patch I can do it myself.

**Comment by dselman** [comment]
Any progress on this or an ETA? I have a need for this.

**Comment by sanketshevkar** [comment]
1. Need handle case for relation and scalars.
2. Write test cases.
By when do you require this? Should a few hours work at max. Sorry, kept it on hold, because I have an interview scheduled this week.
If it's urgent for you I can prioritize it from my side.

**Comment by dselman** [comment]
If you create a draft PR with what you have then I can work on it as well.

**Comment by sanketshevkar** [comment]
1. Created a new issue in concerto-codegen
2. Relationship and Scalar are now handled
3. Need to write tests for field: (fields, enum values, relationships)

I'm trying to raise a PR on concerto-codegen but getting an error, regarding permission
```
remote: Permission to accordproject/concerto-codegen.git denied to sanketshevkar.
fatal: unable to access 'https://github.com/accordproject/concerto-codegen.git/': The requested URL returned error: 403
```

**Comment by dselman** [comment]
Strange. I see other PRs have been created: https://github.com/accordproject/concerto-codegen/branches
You need to fork the repo and then create your PR to merge from your fork back to the main branch.

**Comment by sanketshevkar** [comment]
Ahh 😅
Hadn't forked the repo.
Here's the PR to be reviewed https://github.com/accordproject/concerto-codegen/pull/22
Thanks @dselman

**Comment by sanketshevkar** [comment]
I have completed the tests, can you review the PR? @dselman

**Comment by sanketshevkar** [comment]
Documentation for vocabulary code generation
https://github.com/accordproject/concerto-docs/pull/16

**Comment by dselman** [comment]
This has been implemented.
