### ISSUE TITLE
Allow multiple vocabulary terms per concept and property

### ISSUE THREAD

**Issue by dselman** [accordproject/concerto#645]
# Feature Request 🛍️

At present we only allow a single vocabulary term per concept and per concept property. It would be useful to expand this to support an unlimited set of terms.

## Use Case

Users often need to associate a short term, long term, tooltip, descriptive term etc. with the same property or concept.

**Comment by sanketshevkar** [comment]
Hi @dselman ,
I'll like to pick this up!
