### ISSUE TITLE
Ambiguous imports do not fail validation

### ISSUE THREAD

**Issue by dselman** [accordproject/concerto#648]
# Bug Report 🐛

Models that import a type with the same name as the type in the current namespace and then use it in an `extends` statement do not fail validation.

## Expected Behavior

Model should fail validation as the `extends` statement is ambiguous.

## Current Behavior

Models do not fail validation.

## Possible Solution

1. Ensure that the imported type names do not collide with any of the names in the current model namespace
2. Ensure that the name of a super type is not the same as the name of the type itself

## Steps to Reproduce

test-child.cto

```
namespace test_child@1.0.0

concept Foo {
    o String name
}
```

test.cto

```
namespace test@1.0.0

import test_child@1.0.0.{Foo}

concept Foo extends Foo {
}
```

```
concerto generate sample --concept test@1.0.0.Foo --model ~/Desktop/test.cto ~/Desktop/test-child.cto
```

Generates the output:

```
{
  "$class": "test@1.0.0.Foo",
  "name": "Aliquip."
}
```

### Desktop
 - OS: [e.g. macOS]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 0.22.15]

**Comment by mttrbrts** [comment]
Here's a similar example that I believe is related.

```js

  const model1 = `
  namespace org.acme
  concept Transaction {}
  `;
  
  const model2 = `
  namespace org.acme.ext
  import org.acme.Transaction
  concept MyTransaction extends Transaction {}`;
  
  let modelFile1 = ParserUtil.newModelFile(modelManager, model1);
  modelManager.addModelFile(modelFile1);
  
  let modelFile2 = ParserUtil.newModelFile(modelManager, model2);
  modelManager.addModelFile(modelFile2);

  modelManager.getType('org.acme.ext.MyTransaction').getSuperType()
      .should.equal('org.acme.Transaction');
  // Fails, actual value is `concerto@1.0.0.Transaction`
```

**Comment by mttrbrts** [comment]
Related to #750
