### ISSUE TITLE
Mermaid diagram is incorrect for relationships

### ISSUE THREAD

**Issue by dselman** [accordproject/concerto#649]
# Bug Report 🐛

The mermaid diagram generated for models containing relationships is incorrect.

## Expected Behavior

Relationships should be handled similarly to normal properties.

## Current Behavior

Relationship text is inlines within the class.

## Steps to Reproduce

mermaid.cto

```
namespace mermaid@1.0.0

concept Person identified by id {
    o String id
}

concept Company identified by name {
    o String name
    --> Person ceo
    --> Person[] employees
}
```

```
concerto compile --model ~/Desktop/mermaid.cto --target mermaid --showCompositionRelationships --hideBaseModel 
```

Output:

```
classDiagram
class `mermaid@1.0.0.Person` {
<< concept>>
   + `String` `id`
}

class `mermaid@1.0.0.Company` {
<< concept>>
   + `String` `name`
`mermaid@1.0.0.Company` "1" o-- "1" `mermaid@1.0.0.Person` : ceo
`mermaid@1.0.0.Company` "1" o-- "*" `mermaid@1.0.0.Person` : employees
}

`mermaid@1.0.0.Company` "1" o-- "1" `mermaid@1.0.0.Person` : ceo
`mermaid@1.0.0.Company` "1" o-- "*" `mermaid@1.0.0.Person` : employees
```

Output as a diagram:

<img width="1038" alt="image" src="https://github.com/accordproject/concerto/assets/623108/20dc1d8a-e84e-4dd9-acd3-405e46e75ad9">

[Link](https://mermaid.live/edit#pako:eNrNkbFqAzEMhl9FaGyS0qwmhEL7AIVsQYOFraQHZ-mwfcNx5N3jlOt4bceiRRK_Pn5JMwaLgg5Dz6W8d3zNnEi_KvBJcuIuvu6fX1p8SC6mHmbSwwGCaZChHo-kALABf6q506sH30VPeiNdwbxZGlin3znKSRppbZxwTwi22y3ZilsHQexvlKefKJKG3iaRsuz232zhFhdN--b8OCZh_ZQkhK6lUS489pWw2W9SHqudJg3oah5li-MQucryf3QX7kvrNi9ns-_6dgfgqLWo)

### Desktop
 - OS: [e.g. macOS]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 0.22.15]

**Comment by dselman** [comment]
FYI @mttrbrts

**Comment by utkarsh-shrivastav77** [comment]
hi is this issue still open

**Comment by dselman** [comment]
Yes

**Comment by utkarsh-shrivastav77** [comment]
Sir which files needs to be edited

**Comment by sanketshevkar** [comment]
Hi @dselman 
Is this still open?
If it is, are you expecting an output like this?
```
classDiagram
class `mermaid@1.0.0.Person` {
<< concept>>
   + `String` `id`
}

class `mermaid@1.0.0.Company` {
<< concept>>
   + `String` `name`
   + `Person` `ceo`
   + `Person[]` `employees`
}

`mermaid@1.0.0.Company` "1" o-- "1" `mermaid@1.0.0.Person` : ceo
`mermaid@1.0.0.Company` "1" o-- "*" `mermaid@1.0.0.Person` : employees
```
[Link](https://mermaid.live/edit#pako:eNqNUVFLwzAQ_ivhHl03ljnWGcYY6Ksg7E0jJCTnLDaXkqZgLf3vZqMVFKqSh7v7uHzfd3cdGG8RBJhS1_VdoU9BO0mXiimHwenCHvhimd4DhtqTYp2k3Y4ZTwaruN9LYozNmDrGUNBJMVVYJamXNEFz612lqf2bh7RDNaKjuDLof4BPzwlGV5W-RaxH7SlVCVwC8_P5kE0MKVgS-h_L1W8sX74kQQZDV9p3d55BQnxFhxJESq0ObxKS-9Snm-iPLRkQMTSYQVNZHXE4D4gXXdYJTVYevf9Wg-jgHcQygxYEv16sNxt-s13nq23OV3mfwcflA88AbRF9uB-ufw79J0-Lqo0)

**Comment by sanketshevkar** [comment]
@utkarsh-shrivastav77 are you still interested in solving this? Any progress from your side?

**Comment by dselman** [comment]
Yes, still open.

**Comment by sanketshevkar** [comment]
@dselman I've created a PR for this https://github.com/accordproject/concerto-codegen/pull/39
