### ISSUE TITLE
AP Documentation Sync

### ISSUE THREAD

**Issue by irmerk** [accordproject/concerto#65]
## Tasks
- Ensure layout and structure of README is consistent with other AP repos
- Check if `DEVELOPERS` and `CONTRIBUTING` is tailored to this repo specifically

## Related Issues:
- [Cicero UI Issue 65](https://github.com/accordproject/cicero-ui/issues/65)
- [Markdown Transform Issue 18](https://github.com/accordproject/markdown-transform/issues/18)

## Hacktoberfest:
This issue can provide for multiple pull requests.

**Comment by michizhou** [comment]
I can definitely tackle this issue! Feel free to assign it to me.

**Comment by irmerk** [comment]
Opening back up after 20 days stale.

**Comment by michizhou** [comment]
@irmerk I deeply apologize for not updating you on my progress for this issue. I have been working on this, and should be able to get the documentation ready for review by later today. If you could reassign this issue to me, I would greatly appreciate it. Thank you.

**Comment by irmerk** [comment]
@michizhou what do you think the status is of this issue?

**Comment by michizhou** [comment]
@irmerk I believe this issue is mostly resolved, though we can still leave it open so that others may contribute and fix any documentation mistakes I happened to miss.

**Comment by jeromesimeon** [comment]
I would close it unless we have specific work we should do on it. People can open new issues if they find problems.
