### ISSUE TITLE
Support for defining decorator sets in a human friendly way

### ISSUE THREAD

**Issue by cjablonski76** [accordproject/concerto#659]
# Feature Request 🛍️
Support for defining decorator sets in a human friendly way.

Currently if I want to define decorators inline on the model, it is easy and my preferred way to define decorators.
i.e.
```
concept Car {
   o String make
   @uiHide()
   o String vin
   o String model
}
```
If I want to keep my model clean and separate the concerns of something like the UI application that will render this model, I want to be able to store a decorator set in a separate file instead of inline on the model like I showed above. Currently I would have to either write the serialized JSON form of my desired decorator set, or I would have to
1. write the decorators inline on the model
2. run the command line to output the JSON decorator set file and save that file
3. remove any of my inline decorators

Instead, I would like a way to write up my decorator set(s) in separate files in a business user friendly way.

## Use Case

We have models that will be displayed in a UI component. We want a clean way to store UI specific concerns for how our model(s) should display in our UI component. A decorator set inside a separate file is a great way to manage separation of concerns from the model and expressing UI behavior, but maintain them is not scalable.

**Comment by dselman** [comment]
This sounds useful. We could add API (and expose via command line) that walks a model and grabs all decorators, creating a decorator command set for the decorators found.

E.g.

To apply a decorator command set to a model, saving the modified CTO files to the `./modified` directory:

```
concerto decorators apply --model test.cto  --input decorators.json --output ./modified
```

To create a decorator command set from the decorators on a model (writing the result to `decorators.json`):

```
concerto decorators create --model test.cto
```

Would that meet this requirement? Note that the decorators created in decorators.json on the CTO files would have to be removed by hand...
