### ISSUE TITLE
Update Node version

### ISSUE THREAD

**Issue by DianaLease** [accordproject/concerto#663]
# Feature Request 🛍️

Update to use latest stable version of NodeJS
We should support all current stable versions (and make this our policy moving forward)

**Comment by anablaz** [comment]
Hi @mttrbrts, is this issue still available? :)

**Comment by mttrbrts** [comment]
> Hi @mttrbrts, is this issue still available? :)

Thanks @anablaz, this is already addressed in the v4 branch. https://github.com/accordproject/concerto/pull/762

I'll close the issue, pending release of v4.
