### ISSUE TITLE
Parsed models are not validated against the metamodel

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/concerto#678]
# Bug Report 🐛

The parser doesn't validate the JSON AST against the declared metamodel. This means that we could be creating instances that are not valid with respect to the metamodel. It also makes adding new features more error prone (e.g. https://github.com/accordproject/concerto-metamodel/pull/6) 

## Possible Solution

- We could create a modelManager that we use internally for validation. This would have a small performance hit, but would be limited only to parsing.

**Comment by dselman** [comment]
I agree that this is vital to ensure that parser output conforms to the metamodel.
