### ISSUE TITLE
Consolidate Concerto code into a single repository

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/concerto#68]
**Is your feature request related to a problem? Please describe.**
The code is currently split across two projects: `concerto` and `concerto-tools`. It might be useful for maintenance (versioning, testing) if those are consolidated under a single project. 

**Describe the solution you'd like**
A mono repo using `lerna` which would include:
- `concerto-core` the core model manager/validator
- `concerto-tools` auxiliary code for other schema languages generation
- `concerto-cli` for a command line (See #67)

Possibly, a `concerto-test` project could also be considered.

**Additional context**
This would also align with the structure for other Accord Project repositories (e.g., Cicero and Ergo).

**Comment by mttrbrts** [comment]
:+1:

**Comment by mttrbrts** [comment]
We should also add [concerto-ui](https://github.com/accordproject/concerto-ui) to this list

**Comment by jeromesimeon** [comment]
@mttrbrts I'm less sure I like the idea of moving `concerto-ui` for a couple of reasons:
- I still like the idea of separating the "core" stack from the UI stack -- (they may be on slightly different release schedule, require different kinds of developers expertise, are maintained by different people in the team)
- concerto-ui is already a monorepo...
