### ISSUE TITLE
v4 Planning

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/concerto#706]
# Discussion 🗣

- #703 (Including alignment with Metamodel)
- Strict mode only https://github.com/accordproject/concerto/pull/707
  - Throw on bad metamodel instance #684, by default
  - All models must be versioned
  - Drop support for ImportAll https://github.com/accordproject/concerto/issues/458
- ~~Remove $class from serialization of Maps (done) https://github.com/accordproject/concerto/issues/542~~
- Remove env-var for Map Declarations
- Remove linePositions in parsed AST by default

**Comment by DianaLease** [comment]
To add: Map type decorators

**Comment by DianaLease** [comment]
Drop support for import Type? (breaking)
Add support for aliasing? (non-breaking)

**Comment by DianaLease** [comment]
Remove Loopback as a codegen target?

**Comment by DianaLease** [comment]
Revisit comparison rules in concerto analyze @ekarademir

**Comment by ekarademir** [comment]
> Revisit comparison rules in concerto analyze

Related issue https://github.com/accordproject/concerto/issues/719

**Comment by mttrbrts** [comment]
Closing in favour of the new roadmap project board. https://github.com/orgs/accordproject/projects/15/views/1
