### ISSUE TITLE
Support max length for array and map

### ISSUE THREAD

**Issue by dselman** [accordproject/concerto#732]
# Feature Request 🛍️

Extend the metamodel to support validation facets for the length of an array and the number of keys in a map.

## Use Case

Allows the model to define the maximum number of elements in array or map.

## Possible Solution

1. Update metamodel
2. Update CTO grammar and parser
3. Update AST printer
4. Update validation

**Comment by apoorvsxna** [comment]
Working on this. I am yet to implement the validation.
