### ISSUE TITLE
Vocabulary support for Map Types in Concerto

### ISSUE THREAD

**Issue by sanketshevkar** [accordproject/concerto#735]
# Feature Request 🛍️

Vocabulary support for Map Types in Concerto

## Use Case

Vocabularies should be able to get applied on Map Types (MapDeclaration, MapKeyType, MapValueType).

## Detailed Description

```
@Term("Dictionary")
map Dictionary {
  @Term("Key")
  o String
  @Term("Value")
  o Boolean
}

@Term("Dictionary")
map Employees {
  @Term("Employee Id")
  @Term_description("System generated Id for an employee")
  @Term_tooltip("Employee Identification Number")
  o String
  @Term("Employee Name")
  o String
}

```

**Comment by dselman** [comment]
Looks great. A design pattern that uses scalars for map keys would be good to test and promote:

```
@Term("Employee Id") 
scalar EmployeeId extends String

concept Employee identified by id {
   o EmployeeId id
   o String name
   o Integer age
}

@Term("Employee Directory")
map EmployeeDirectory {
   o EmployeeId
   o Employee
}
```

**Comment by sanketshevkar** [comment]
Need changes in VocabularyManager.js & Vocabulary.js.  
In VocabularyManager the changes would be around the generateDecoratorCommands.
Since MapDeclarations have KeyType and ValueType which are different from Property, which might need to have separate method term resolution for them.
- resolvePropertyTerms (previously [resolveTerms](https://github.com/accordproject/concerto/blob/aca5c3e647406b0beb2203c4fe925265e666e136/packages/concerto-vocabulary/lib/vocabularymanager.js#L205))
- resolvePropertyTerm (previously [resolveTerm](https://github.com/accordproject/concerto/blob/aca5c3e647406b0beb2203c4fe925265e666e136/packages/concerto-vocabulary/lib/vocabularymanager.js#L187))
- getPropertyTerms (previously [getTerms ](https://github.com/accordproject/concerto/blob/aca5c3e647406b0beb2203c4fe925265e666e136/packages/concerto-vocabulary/lib/vocabularymanager.js#L251))
- getPropertyTerm(previously [getTerm](https://github.com/accordproject/concerto/blob/aca5c3e647406b0beb2203c4fe925265e666e136/packages/concerto-vocabulary/lib/vocabularymanager.js#L222))
- getMapKeyTerms
- getMapKeyTerm
- getMapPropertyTerms
- getMapPropertyTerm

In Vocabulary.js the [validate ](https://github.com/accordproject/concerto/blob/aca5c3e647406b0beb2203c4fe925265e666e136/packages/concerto-vocabulary/lib/vocabulary.js#L146)method needs to be updated to capture missing and additional terms for MapDeclaration, MapKey and MapValue. 
Similar to VocabularyManager we might need different methods to get terms for properties, mapkeytypes and mapvaluetypes

**Comment by sanketshevkar** [comment]
> Looks great. A design pattern that uses scalars for map keys would be good to test and promote:
> 
> ```
> @Term("Employee Id") 
> scalar EmployeeId extends String
> 
> concept Employee identified by id {
>    o EmployeeId id
>    o String name
>    o Integer age
> }
> 
> @Term("Employee Directory")
> map EmployeeDirectory {
>    o EmployeeId
>    o Employee
> }
> ```

Will this mean that the key type of `EmployeeId` in the map inherits its vocabulary term from the Scalar type that we have defined above?
If yes,
We also need a Term decorator separately for a key type if its of String of dateTime value. In that case which term decorator should the scalar type key inherit? One defined at the Scalar declaration level or at key level?
