### ISSUE TITLE
Concerto Core has the wrong package name

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/concerto#74]
**Describe the bug**
Wrong package name.

The structure of the lerna packages in the code is:
```
concerto-core
concerto-tools
concerto-cli
```

But the package name (and the published package on npmjs) for `concerto-core` is still `concerto`. I think it would make sense to change that to avoid confusion, and align with other Accord Project packages structure/naming.

Corresponding line, I believe:
https://github.com/accordproject/concerto/blob/9f324a35c0d2f5f50ddeb64b04a1e819e7487143/packages/concerto-core/package.json#L2

**Comment by Niladri24dutta** [comment]
@jeromesimeon created a PR to update the package name

**Comment by jeromesimeon** [comment]
Thanks @Niladri24dutta ! That's great. I would love to get @mttrbrts 's feedback on this issue since he did the refactoring into a monorepo.

**Comment by mttrbrts** [comment]
@jeromesimeon I've left some minor comments in the PR. otherwise it LGTM 👍

**Comment by jeromesimeon** [comment]
@mttrbrts Great thanks! I wanted to make sure you agree with the issue in the first place!

**Comment by jeromesimeon** [comment]
A few things that should be done for this:
- Make sure all references across packages use the new name. Most of them are in the `concerto-tools` package. Here is a grep on my local copy:
```

Here is a grep of the references on my local machine:
```
bash-3.2$ grep -r require packages/*/lib | grep concerto | grep accordproject | grep -v '@accordproject/concerto-tools'
packages/concerto-cli/lib/commands.js:const ModelManager = require('@accordproject/concerto').ModelManager;
packages/concerto-cli/lib/commands.js:const ModelFile = require('@accordproject/concerto').ModelFile;
packages/concerto-cli/lib/commands.js:const DefaultModelFileLoader = require('@accordproject/concerto').DefaultModelFileLoader;
packages/concerto-cli/lib/commands.js:const FileWriter = require('@accordproject/concerto').FileWriter;
packages/concerto-tools/lib/codegen/fromcto/plantuml/plantumlvisitor.js:const ModelFile = require('@accordproject/concerto').ModelFile;
packages/concerto-tools/lib/codegen/fromcto/plantuml/plantumlvisitor.js:const ModelManager = require('@accordproject/concerto').ModelManager;
packages/concerto-tools/lib/codegen/fromcto/plantuml/plantumlvisitor.js:const ClassDeclaration = require('@accordproject/concerto').ClassDeclaration;
packages/concerto-tools/lib/codegen/fromcto/plantuml/plantumlvisitor.js:const TransactionDeclaration = require('@accordproject/concerto').TransactionDeclaration;
packages/concerto-tools/lib/codegen/fromcto/plantuml/plantumlvisitor.js:const AssetDeclaration = require('@accordproject/concerto').AssetDeclaration;
packages/concerto-tools/lib/codegen/fromcto/plantuml/plantumlvisitor.js:const ParticipantDeclaration = require('@accordproject/concerto').ParticipantDeclaration;
packages/concerto-tools/lib/codegen/fromcto/plantuml/plantumlvisitor.js:const EnumDeclaration = require('@accordproject/concerto').EnumDeclaration;
packages/concerto-tools/lib/codegen/fromcto/plantuml/plantumlvisitor.js:const Field = require('@accordproject/concerto').Field;
packages/concerto-tools/lib/codegen/fromcto/plantuml/plantumlvisitor.js:const RelationshipDeclaration = require('@accordproject/concerto').RelationshipDeclaration;
packages/concerto-tools/lib/codegen/fromcto/plantuml/plantumlvisitor.js:const EnumValueDeclaration = require('@accordproject/concerto').EnumValueDeclaration;
packages/concerto-tools/lib/codegen/fromcto/golang/golangvisitor.js:const AssetDeclaration = require('@accordproject/concerto').AssetDeclaration;
packages/concerto-tools/lib/codegen/fromcto/golang/golangvisitor.js:const ClassDeclaration = require('@accordproject/concerto').ClassDeclaration;
packages/concerto-tools/lib/codegen/fromcto/golang/golangvisitor.js:const EnumDeclaration = require('@accordproject/concerto').EnumDeclaration;
packages/concerto-tools/lib/codegen/fromcto/golang/golangvisitor.js:const ConceptDeclaration = require('@accordproject/concerto').ConceptDeclaration;
packages/concerto-tools/lib/codegen/fromcto/golang/golangvisitor.js:const EnumValueDeclaration = require('@accordproject/concerto').EnumValueDeclaration;
packages/concerto-tools/lib/codegen/fromcto/golang/golangvisitor.js:const Field = require('@accordproject/concerto').Field;
packages/concerto-tools/lib/codegen/fromcto/golang/golangvisitor.js:const ModelFile = require('@accordproject/concerto').ModelFile;
packages/concerto-tools/lib/codegen/fromcto/golang/golangvisitor.js:const ModelManager = require('@accordproject/concerto').ModelManager;
packages/concerto-tools/lib/codegen/fromcto/golang/golangvisitor.js:const RelationshipDeclaration = require('@accordproject/concerto').RelationshipDeclaration;
packages/concerto-tools/lib/codegen/fromcto/golang/golangvisitor.js:const TransactionDeclaration = require('@accordproject/concerto').TransactionDeclaration;
packages/concerto-tools/lib/codegen/fromcto/golang/golangvisitor.js:const ModelUtil = require('@accordproject/concerto').ModelUtil;
packages/concerto-tools/lib/codegen/fromcto/typescript/typescriptvisitor.js:const ModelManager = require('@accordproject/concerto').ModelManager;
packages/concerto-tools/lib/codegen/fromcto/typescript/typescriptvisitor.js:const ModelUtil = require('@accordproject/concerto').ModelUtil;
packages/concerto-tools/lib/codegen/fromcto/typescript/typescriptvisitor.js:const ModelFile = require('@accordproject/concerto').ModelFile;
packages/concerto-tools/lib/codegen/fromcto/typescript/typescriptvisitor.js:const ClassDeclaration = require('@accordproject/concerto').ClassDeclaration;
packages/concerto-tools/lib/codegen/fromcto/typescript/typescriptvisitor.js:const Field = require('@accordproject/concerto').Field;
packages/concerto-tools/lib/codegen/fromcto/typescript/typescriptvisitor.js:const RelationshipDeclaration = require('@accordproject/concerto').RelationshipDeclaration;
packages/concerto-tools/lib/codegen/fromcto/typescript/typescriptvisitor.js:const EnumDeclaration = require('@accordproject/concerto').EnumDeclaration;
packages/concerto-tools/lib/codegen/fromcto/typescript/typescriptvisitor.js:const EnumValueDeclaration = require('@accordproject/concerto').EnumValueDeclaration;
packages/concerto-tools/lib/codegen/fromcto/xmlschema/xmlschemavisitor.js:const ModelFile = require('@accordproject/concerto').ModelFile;
packages/concerto-tools/lib/codegen/fromcto/xmlschema/xmlschemavisitor.js:const ModelManager = require('@accordproject/concerto').ModelManager;
packages/concerto-tools/lib/codegen/fromcto/xmlschema/xmlschemavisitor.js:const ModelUtil = require('@accordproject/concerto').ModelUtil;
packages/concerto-tools/lib/codegen/fromcto/xmlschema/xmlschemavisitor.js:const ClassDeclaration = require('@accordproject/concerto').ClassDeclaration;
packages/concerto-tools/lib/codegen/fromcto/xmlschema/xmlschemavisitor.js:const EnumDeclaration = require('@accordproject/concerto').EnumDeclaration;
packages/concerto-tools/lib/codegen/fromcto/xmlschema/xmlschemavisitor.js:const Field = require('@accordproject/concerto').Field;
packages/concerto-tools/lib/codegen/fromcto/xmlschema/xmlschemavisitor.js:const RelationshipDeclaration = require('@accordproject/concerto').RelationshipDeclaration;
packages/concerto-tools/lib/codegen/fromcto/xmlschema/xmlschemavisitor.js:const EnumValueDeclaration = require('@accordproject/concerto').EnumValueDeclaration;
packages/concerto-tools/lib/codegen/fromcto/java/javavisitor.js:const ModelManager = require('@accordproject/concerto').ModelManager;
packages/concerto-tools/lib/codegen/fromcto/java/javavisitor.js:const ModelUtil = require('@accordproject/concerto').ModelUtil;
packages/concerto-tools/lib/codegen/fromcto/java/javavisitor.js:const ModelFile = require('@accordproject/concerto').ModelFile;
packages/concerto-tools/lib/codegen/fromcto/java/javavisitor.js:const ClassDeclaration = require('@accordproject/concerto').ClassDeclaration;
packages/concerto-tools/lib/codegen/fromcto/java/javavisitor.js:const Field = require('@accordproject/concerto').Field;
packages/concerto-tools/lib/codegen/fromcto/java/javavisitor.js:const RelationshipDeclaration = require('@accordproject/concerto').RelationshipDeclaration;
packages/concerto-tools/lib/codegen/fromcto/java/javavisitor.js:const EnumDeclaration = require('@accordproject/concerto').EnumDeclaration;
packages/concerto-tools/lib/codegen/fromcto/java/javavisitor.js:const EnumValueDeclaration = require('@accordproject/concerto').EnumValueDeclaration;
packages/concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js:const AssetDeclaration = require('@accordproject/concerto').AssetDeclaration;
packages/concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js:const ClassDeclaration = require('@accordproject/concerto').ClassDeclaration;
packages/concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js:const EnumDeclaration = require('@accordproject/concerto').EnumDeclaration;
packages/concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js:const ConceptDeclaration = require('@accordproject/concerto').ConceptDeclaration;
packages/concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js:const EnumValueDeclaration = require('@accordproject/concerto').EnumValueDeclaration;
packages/concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js:const Field = require('@accordproject/concerto').Field;
packages/concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js:const ModelFile = require('@accordproject/concerto').ModelFile;
packages/concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js:const ModelManager = require('@accordproject/concerto').ModelManager;
packages/concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js:const RelationshipDeclaration = require('@accordproject/concerto').RelationshipDeclaration;
packages/concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js:const TransactionDeclaration = require('@accordproject/concerto').TransactionDeclaration;
packages/concerto-tools/lib/codegen/fromcto/loopback/loopbackvisitor.js:const AssetDeclaration = require('@accordproject/concerto').AssetDeclaration;
packages/concerto-tools/lib/codegen/fromcto/loopback/loopbackvisitor.js:const ParticipantDeclaration = require('@accordproject/concerto').ParticipantDeclaration;
packages/concerto-tools/lib/codegen/fromcto/loopback/loopbackvisitor.js:const ConceptDeclaration = require('@accordproject/concerto').ConceptDeclaration;
packages/concerto-tools/lib/codegen/fromcto/loopback/loopbackvisitor.js:const EnumDeclaration = require('@accordproject/concerto').EnumDeclaration;
packages/concerto-tools/lib/codegen/fromcto/loopback/loopbackvisitor.js:const EnumValueDeclaration = require('@accordproject/concerto').EnumValueDeclaration;
packages/concerto-tools/lib/codegen/fromcto/loopback/loopbackvisitor.js:const EventDeclaration = require('@accordproject/concerto').EventDeclaration;
packages/concerto-tools/lib/codegen/fromcto/loopback/loopbackvisitor.js:const Field = require('@accordproject/concerto').Field;
packages/concerto-tools/lib/codegen/fromcto/loopback/loopbackvisitor.js:const ModelFile = require('@accordproject/concerto').ModelFile;
packages/concerto-tools/lib/codegen/fromcto/loopback/loopbackvisitor.js:const ModelManager = require('@accordproject/concerto').ModelManager;
packages/concerto-tools/lib/codegen/fromcto/loopback/loopbackvisitor.js:const RelationshipDeclaration = require('@accordproject/concerto').RelationshipDeclaration;
packages/concerto-tools/lib/codegen/fromcto/loopback/loopbackvisitor.js:const TransactionDeclaration = require('@accordproject/concerto').TransactionDeclaration;
```
- Review the READMEs/Dev instructions to make sure they refer to the new name if necessary.
- I am not entirely clear, but there might be some build scripts that also refer to the package (this could be checked later).

Once the tests pass, I'll keep an eye on the deployment to npm and can help with that if need be.

**Comment by Niladri24dutta** [comment]
> 
> 
> A few things that should be done for this:
> 
>     * Make sure all references across packages use the new name. Most of them are in the `concerto-tools` package. Here is a grep on my local copy:
> 
> 
> ```
> bash-3.2$ grep -r require packages/*/lib | grep concerto | grep accordproject | grep -v '@accordproject/concerto-tools'
> packages/concerto-cli/lib/commands.js:const ModelManager = require('@accordproject/concerto').ModelManager;
> packages/concerto-cli/lib/commands.js:const ModelFile = require('@accordproject/concerto').ModelFile;
> packages/concerto-cli/lib/commands.js:const DefaultModelFileLoader = require('@accordproject/concerto').DefaultModelFileLoader;
> packages/concerto-cli/lib/commands.js:const FileWriter = require('@accordproject/concerto').FileWriter;
> packages/concerto-tools/lib/codegen/fromcto/plantuml/plantumlvisitor.js:const ModelFile = require('@accordproject/concerto').ModelFile;
> packages/concerto-tools/lib/codegen/fromcto/plantuml/plantumlvisitor.js:const ModelManager = require('@accordproject/concerto').ModelManager;
> packages/concerto-tools/lib/codegen/fromcto/plantuml/plantumlvisitor.js:const ClassDeclaration = require('@accordproject/concerto').ClassDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/plantuml/plantumlvisitor.js:const TransactionDeclaration = require('@accordproject/concerto').TransactionDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/plantuml/plantumlvisitor.js:const AssetDeclaration = require('@accordproject/concerto').AssetDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/plantuml/plantumlvisitor.js:const ParticipantDeclaration = require('@accordproject/concerto').ParticipantDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/plantuml/plantumlvisitor.js:const EnumDeclaration = require('@accordproject/concerto').EnumDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/plantuml/plantumlvisitor.js:const Field = require('@accordproject/concerto').Field;
> packages/concerto-tools/lib/codegen/fromcto/plantuml/plantumlvisitor.js:const RelationshipDeclaration = require('@accordproject/concerto').RelationshipDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/plantuml/plantumlvisitor.js:const EnumValueDeclaration = require('@accordproject/concerto').EnumValueDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/golang/golangvisitor.js:const AssetDeclaration = require('@accordproject/concerto').AssetDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/golang/golangvisitor.js:const ClassDeclaration = require('@accordproject/concerto').ClassDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/golang/golangvisitor.js:const EnumDeclaration = require('@accordproject/concerto').EnumDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/golang/golangvisitor.js:const ConceptDeclaration = require('@accordproject/concerto').ConceptDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/golang/golangvisitor.js:const EnumValueDeclaration = require('@accordproject/concerto').EnumValueDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/golang/golangvisitor.js:const Field = require('@accordproject/concerto').Field;
> packages/concerto-tools/lib/codegen/fromcto/golang/golangvisitor.js:const ModelFile = require('@accordproject/concerto').ModelFile;
> packages/concerto-tools/lib/codegen/fromcto/golang/golangvisitor.js:const ModelManager = require('@accordproject/concerto').ModelManager;
> packages/concerto-tools/lib/codegen/fromcto/golang/golangvisitor.js:const RelationshipDeclaration = require('@accordproject/concerto').RelationshipDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/golang/golangvisitor.js:const TransactionDeclaration = require('@accordproject/concerto').TransactionDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/golang/golangvisitor.js:const ModelUtil = require('@accordproject/concerto').ModelUtil;
> packages/concerto-tools/lib/codegen/fromcto/typescript/typescriptvisitor.js:const ModelManager = require('@accordproject/concerto').ModelManager;
> packages/concerto-tools/lib/codegen/fromcto/typescript/typescriptvisitor.js:const ModelUtil = require('@accordproject/concerto').ModelUtil;
> packages/concerto-tools/lib/codegen/fromcto/typescript/typescriptvisitor.js:const ModelFile = require('@accordproject/concerto').ModelFile;
> packages/concerto-tools/lib/codegen/fromcto/typescript/typescriptvisitor.js:const ClassDeclaration = require('@accordproject/concerto').ClassDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/typescript/typescriptvisitor.js:const Field = require('@accordproject/concerto').Field;
> packages/concerto-tools/lib/codegen/fromcto/typescript/typescriptvisitor.js:const RelationshipDeclaration = require('@accordproject/concerto').RelationshipDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/typescript/typescriptvisitor.js:const EnumDeclaration = require('@accordproject/concerto').EnumDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/typescript/typescriptvisitor.js:const EnumValueDeclaration = require('@accordproject/concerto').EnumValueDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/xmlschema/xmlschemavisitor.js:const ModelFile = require('@accordproject/concerto').ModelFile;
> packages/concerto-tools/lib/codegen/fromcto/xmlschema/xmlschemavisitor.js:const ModelManager = require('@accordproject/concerto').ModelManager;
> packages/concerto-tools/lib/codegen/fromcto/xmlschema/xmlschemavisitor.js:const ModelUtil = require('@accordproject/concerto').ModelUtil;
> packages/concerto-tools/lib/codegen/fromcto/xmlschema/xmlschemavisitor.js:const ClassDeclaration = require('@accordproject/concerto').ClassDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/xmlschema/xmlschemavisitor.js:const EnumDeclaration = require('@accordproject/concerto').EnumDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/xmlschema/xmlschemavisitor.js:const Field = require('@accordproject/concerto').Field;
> packages/concerto-tools/lib/codegen/fromcto/xmlschema/xmlschemavisitor.js:const RelationshipDeclaration = require('@accordproject/concerto').RelationshipDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/xmlschema/xmlschemavisitor.js:const EnumValueDeclaration = require('@accordproject/concerto').EnumValueDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/java/javavisitor.js:const ModelManager = require('@accordproject/concerto').ModelManager;
> packages/concerto-tools/lib/codegen/fromcto/java/javavisitor.js:const ModelUtil = require('@accordproject/concerto').ModelUtil;
> packages/concerto-tools/lib/codegen/fromcto/java/javavisitor.js:const ModelFile = require('@accordproject/concerto').ModelFile;
> packages/concerto-tools/lib/codegen/fromcto/java/javavisitor.js:const ClassDeclaration = require('@accordproject/concerto').ClassDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/java/javavisitor.js:const Field = require('@accordproject/concerto').Field;
> packages/concerto-tools/lib/codegen/fromcto/java/javavisitor.js:const RelationshipDeclaration = require('@accordproject/concerto').RelationshipDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/java/javavisitor.js:const EnumDeclaration = require('@accordproject/concerto').EnumDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/java/javavisitor.js:const EnumValueDeclaration = require('@accordproject/concerto').EnumValueDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js:const AssetDeclaration = require('@accordproject/concerto').AssetDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js:const ClassDeclaration = require('@accordproject/concerto').ClassDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js:const EnumDeclaration = require('@accordproject/concerto').EnumDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js:const ConceptDeclaration = require('@accordproject/concerto').ConceptDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js:const EnumValueDeclaration = require('@accordproject/concerto').EnumValueDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js:const Field = require('@accordproject/concerto').Field;
> packages/concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js:const ModelFile = require('@accordproject/concerto').ModelFile;
> packages/concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js:const ModelManager = require('@accordproject/concerto').ModelManager;
> packages/concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js:const RelationshipDeclaration = require('@accordproject/concerto').RelationshipDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/jsonschema/jsonschemavisitor.js:const TransactionDeclaration = require('@accordproject/concerto').TransactionDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/loopback/loopbackvisitor.js:const AssetDeclaration = require('@accordproject/concerto').AssetDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/loopback/loopbackvisitor.js:const ParticipantDeclaration = require('@accordproject/concerto').ParticipantDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/loopback/loopbackvisitor.js:const ConceptDeclaration = require('@accordproject/concerto').ConceptDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/loopback/loopbackvisitor.js:const EnumDeclaration = require('@accordproject/concerto').EnumDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/loopback/loopbackvisitor.js:const EnumValueDeclaration = require('@accordproject/concerto').EnumValueDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/loopback/loopbackvisitor.js:const EventDeclaration = require('@accordproject/concerto').EventDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/loopback/loopbackvisitor.js:const Field = require('@accordproject/concerto').Field;
> packages/concerto-tools/lib/codegen/fromcto/loopback/loopbackvisitor.js:const ModelFile = require('@accordproject/concerto').ModelFile;
> packages/concerto-tools/lib/codegen/fromcto/loopback/loopbackvisitor.js:const ModelManager = require('@accordproject/concerto').ModelManager;
> packages/concerto-tools/lib/codegen/fromcto/loopback/loopbackvisitor.js:const RelationshipDeclaration = require('@accordproject/concerto').RelationshipDeclaration;
> packages/concerto-tools/lib/codegen/fromcto/loopback/loopbackvisitor.js:const TransactionDeclaration = require('@accordproject/concerto').TransactionDeclaration;
> ```
> 
>     * Review the READMEs/Dev instructions to make sure they refer to the new name if necessary.
> 
>     * I am not entirely clear, but there might be some build scripts that also refer to the package (this could be checked later).
> 
> 
> Once the tests pass, I'll keep an eye on the deployment to npm and can help with that if need be.

I have made the requested changes in the PR

**Comment by jeromesimeon** [comment]
Well done @Niladri24dutta ! You PR is merged now, and the corresponding package is published on npm:
https://www.npmjs.com/package/@accordproject/concerto-core

**Comment by Niladri24dutta** [comment]
> Well done @Niladri24dutta ! You PR is merged now, and the corresponding package is published on npm:
> https://www.npmjs.com/package/@accordproject/concerto-core
@jeromesimeon 
Just a question in the installation of npm document above , do we need to update the commands which refers to  `@accordproject/concerto`  e.g `npm install @accordproject/concerto --save`

**Comment by jeromesimeon** [comment]
> Well done @Niladri24dutta ! You PR is merged now, and the corresponding package is published on npm:
> https://www.npmjs.com/package/@accordproject/concerto-core
> @jeromesimeon
> Just a question in the installation of npm document above , do we need to update the commands which refers to `@accordproject/concerto` e.g `npm install @accordproject/concerto --save`

I think this should be fixed actually. It's probably just npm getting a little confused since we haven't had a first release yet. If you look at the latest tagged "unstable" version you have:
https://www.npmjs.com/package/@accordproject/concerto-core/v/0.80.4-20191004042248

(or in the repo itself)

**Comment by Niladri24dutta** [comment]
@jeromesimeon that makes sense now. is this PR will be elligible for hacktoberfest?
