### ISSUE TITLE
Throw error on validation of model with decorators with type reference if type not present

### ISSUE THREAD

**Issue by sanketshevkar** [accordproject/concerto#798]
# Bug Report 🐛

Currently if we add decorator with type reference, it does not check if the type exists within the namespace. We should be throwing error if the type is not imported or not present within the namespace
```
namespace car@1.0.0

import workshop@1.0.0.{Color}

concept Owner {
   o String ownerName
}

// should throw error on model validation as Train is not present in namespace
@colorOptions(Train)
concept CarColor {}
```
Might have to fix this issue first https://github.com/accordproject/concerto/issues/797
## Expected Behavior

Should throw error on validation

## Steps to Reproduce

1. Add the above model to model manager and validate, will not throw error
2. 
3.
4.

**Comment by subhajit20** [comment]
Hey @sanketshevkar  is this the correct file to be changed?
https://github.com/accordproject/concerto/blob/ed6c188d4a03dbc5252a691b51087ad050ee1705/packages/concerto-core/lib/introspect/decorator.js#L33-L45

**Comment by sanketshevkar** [comment]
> Hey @sanketshevkar is this the correct file to be changed?

Yes!

**Comment by ahmad-kashkoush** [comment]
Hey @sanketshevkar , I've Created a PR of My changes, I hope to get a Feedback

**Comment by dselman** [comment]
Fixed in main.
