### ISSUE TITLE
Namespaces vulnerable to ReDoS

### ISSUE THREAD

**Issue by porrungroj** [accordproject/concerto#806]
Here's a general description of ReDoS. https://en.wikipedia.org/wiki/ReDoS

I didn't investigate any further, but I suspect there may be other validation that's vulnerable as well.
## Steps to Reproduce
Use a malicious namespace that forces exponential backtracking with an invalid character at the end. E.g.
```ts
`${'a_'.repeat(100)}+`
```

**Comment by mttrbrts** [comment]
The ModelManager allows client applications to specify their own Regular Expression engine to protect against this kind of attack. For example, you should choose the [RE2 engine](https://github.com/uhop/node-re2/) if your application accepts arbitrary user input for regular expressions.

ModelManager docs: https://concerto.accordproject.org/docs/reference/api/ref-concerto-js-api#new_module_concerto-core.BaseModelManager_new
