### ISSUE TITLE
Automated API Verification should prompt user to change the Typescript definition

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/concerto#82]
**Is your feature request related to a problem? Please describe.**
Now that Concerto has a TypeScript definition, #80 we need to make sure that it is kept up to date. Doing this automatically will be difficult because JS doesn't have all of the info required to generate TS definitions. However, we can alert developers who make API changes using the existing `versionchecker.js` script.

**Describe the solution you'd like**
Extend the [`versionchecker.js`](https://github.com/accordproject/concerto/packages/concerto-core/lib/tools/versionchecker.js ) script to remind users who make API changes to also update the `packages/concerto-core/types/index.d.ts` file.

**Comment by erikbfeeley** [comment]
Hey, just forked and started to work on this issue!
