### ISSUE TITLE
Standardize/localize error messaging

### ISSUE THREAD

**Issue by DianaLease** [accordproject/concerto#838]
# Feature Request 🛍️

Clean up error messages to use Globalization class to localize error messaging

**Comment by AbhinRustagi** [comment]
Is this still valid? I would like to work on this

**Comment by dselman** [comment]
> Is this still valid? I would like to work on this

Yes, this would be a great contribution. There are quite a few hardcoded error messages that would need to be externalised. I recommend doing a couple and submitting a PR for review before tackling the rest, just to ensure you are on the right track.

**Comment by AbhinRustagi** [comment]
That sounds fair. I'll get started on this, and submit a PR for review, and take it from there depending any comments or suggestions!

**Comment by AbhinRustagi** [comment]
@dselman Please have a look
