### ISSUE TITLE
Factory doesn't generate empty entities

### ISSUE THREAD

**Issue by ekarademir** [accordproject/concerto#844]
Factory class advertises an option to generate empty entity instead of a "sample", however the option has no effect
# Bug Report 🐛

As it's being used by the CLI generate command [here](https://github.com/accordproject/concerto-cli/blob/cb5c1b33d9b51c7189e99f8b7d495f6af77e829f/lib/commands.js#L302), and being passed onto the factory class [here](https://github.com/accordproject/concerto-cli/blob/cb5c1b33d9b51c7189e99f8b7d495f6af77e829f/lib/commands.js#L320), there should be an option to generate empty objects as advertised [here](https://github.com/accordproject/concerto/blob/4c327bd9c6bee2abb49cb67e6c6ea6277c4ab681/packages/concerto-core/lib/factory.js#L80-L81).

But that option is simply being ignored.

## Expected Behavior

That the factory returns an entity with empty values

## Current Behavior

Returns sampled data as values

## Steps to Reproduce

1. Use the setup outlined in the [CLI command](https://github.com/accordproject/concerto-cli/blob/cb5c1b33d9b51c7189e99f8b7d495f6af77e829f/lib/commands.js#L316-L343).
2. Inspect the JSON document

### Desktop
 - OS: macOS
 - Browser: Chrome & Node

**Comment by mttrbrts** [comment]
@ekarademir do the String properties in your model have min/max length validators?

We made the decision when adding those that the output of the value generators should always be a valid instance. This forces us to generate some sample data even when using the `empty` mode.

I think that there's scope to improve the logic here, for example:
- Generate only using spaces, ` ` when in `empty` mode
- Always use the min length when specified in `empty` mode
