### ISSUE TITLE
Add coverall coverage report and badge

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/concerto#88]
We should report test coverage for the whole monorepo, including a badge in the README.

Tasks:
- [x] Add test coverage to `Cicero-cli`
- [x] Add combined coverage report for all the packages and publish to coverall
- [x] Add badge to README

**Comment by Niladri24dutta** [comment]
@jeromesimeon  is there any available badge that we can use for test coverage? I think we already have test coverage in travis build

**Comment by jeromesimeon** [comment]
@Niladri24dutta You can find test coverage badge examples in some of the other projects. e.g., https://github.com/accordproject/cicero/blob/master/README.md

The issue here is that I don't think we are reporting those properly to coverall. Also the `cicero-cli` does not have code coverage in place.
